// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// Code generated by tygo from server/internal/models. DO NOT EDIT.
// Regenerate: cd server && go run github.com/gzuidhof/tygo@v0.2.21 generate

//////////
// source: alert.go

/**
 * CommandTrigger defines a remote command to execute automatically when an alert fires.
 */
export interface CommandTrigger {
  module: string; // e.g. "processes", "journal", "docker", "systemd"
  action: string; // e.g. "list", "read", "restart"
  target?: string; // e.g. service name, container name
  payload?: string; // optional JSON payload
}
/**
 * ProxmoxMetricScope defines how a Proxmox metric should be evaluated.
 * ScopeMode can be one of: global, connection, node, storage.
 */
export interface ProxmoxMetricScope {
  scope_mode?: string;
  connection_id?: string;
  node_id?: string;
  storage_id?: string;
  guest_id?: string;
  disk_id?: string;
}
/**
 * DockerMetricScope defines how a Docker metric should be evaluated.
 * ScopeMode can be one of: host, container, compose_project.
 * HostID is always required. ContainerID or ProjectName are required for their respective modes.
 * WarnStates and CritStates are used by docker_container_state to select which container states trigger each severity.
 */
export interface DockerMetricScope {
  scope_mode: string;
  host_id: string;
  container_id?: string; // DB UUID of docker_containers row
  project_name?: string; // compose project name
  warn_states?: string[]; // container states triggering warn
  crit_states?: string[]; // container states triggering crit
}
export type AlertSourceType = string;
export const AlertSourceAgent: AlertSourceType = "agent";
export const AlertSourceProxmox: AlertSourceType = "proxmox";
export const AlertSourceDocker: AlertSourceType = "docker";
/**
 * AlertActions holds the consolidated notification configuration for an alert rule.
 * Stored as a single JSONB column in the database.
 */
export interface AlertActions {
  channels: string[]; // e.g. ["smtp", "ntfy", "browser"]
  smtp_to?: string; // SMTP recipient address(es)
  ntfy_topic?: string; // ntfy push notification topic
  cooldown?: number /* int */; // seconds between re-notifications (0 = no cooldown)
  command_trigger?: CommandTrigger; // optional command to run on alert
}
export interface AlertRule {
  id: number /* int64 */;
  name?: string;
  source_type?: AlertSourceType;
  host_id?: string;
  proxmox_scope?: ProxmoxMetricScope;
  docker_scope?: DockerMetricScope;
  metric: string;
  operator: string;
  threshold_warn?: number /* float64 */;
  threshold_crit?: number /* float64 */;
  threshold_clear_warn?: number /* float64 */; // hysteresis for warn
  threshold_clear_crit?: number /* float64 */; // hysteresis for crit
  duration_seconds: number /* int */;
  actions: AlertActions; // stored as JSONB in DB
  last_fired?: string;
  enabled: boolean;
  created_at: string;
  updated_at?: string;
  active_incident_count: number /* int */;
}
export interface AlertIncident {
  id: number /* int64 */;
  rule_id?: number /* int64 */;
  host_id: string;
  severity: string; // "warn" or "crit"
  triggered_at: string;
  resolved_at?: string;
  value: number /* float64 */;
  /**
   * Enriched post-fetch (not DB columns): Docker synthetic IDs resolution
   */
  value_label?: string;
  link_host_id?: string;
}
export interface NotificationItem {
  id: string;
  type: string;
  rule_id?: number /* int64 */;
  host_id: string;
  host_name: string;
  source_type?: string;
  source_label?: string;
  rule_name: string;
  metric: string;
  severity?: string;
  status?: string;
  tracker_id?: string;
  tracker_type?: string;
  release_url?: string;
  release_name?: string;
  version?: string;
  value: number /* float64 */;
  triggered_at: string;
  resolved_at?: string;
  browser_notify: boolean;
  /**
   * CurrentValue / ClearThreshold are populated only for active alert
   * incidents: the live metric value and the threshold it must cross to
   * resolve (hysteresis clear threshold, or the trigger threshold otherwise).
   */
  current_value?: number /* float64 */;
  clear_threshold?: number /* float64 */;
  operator?: string;
  /**
   * Docker synthetic ID resolution: real host to navigate to, and human state label
   */
  link_host_id?: string;
  value_label?: string;
}
/**
 * PushSubscription represents a Web Push (VAPID) subscription for a user's browser/device.
 * Stored server-side so that alert notifications can be delivered even when the app is closed.
 */
export interface PushSubscription {
  id: number /* int64 */;
  username: string;
  endpoint: string;
  p256dh: string;
  auth: string;
  user_agent?: string;
  created_at: string;
}
export interface AlertRuleCreate {
  name: string;
  enabled: boolean;
  source_type: AlertSourceType;
  host_id?: string;
  proxmox_scope?: ProxmoxMetricScope;
  docker_scope?: DockerMetricScope;
  metric: string;
  operator: string;
  threshold_warn: number /* float64 */;
  threshold_crit: number /* float64 */;
  threshold_clear_warn?: number /* float64 */;
  threshold_clear_crit?: number /* float64 */;
  duration: number /* int */;
  actions: AlertActions;
}
export interface AlertRuleUpdate {
  name?: string;
  enabled?: boolean;
  source_type?: AlertSourceType;
  host_id?: string;
  proxmox_scope?: ProxmoxMetricScope;
  docker_scope?: DockerMetricScope;
  metric?: string;
  operator?: string;
  threshold_warn?: number /* float64 */;
  threshold_crit?: number /* float64 */;
  threshold_clear_warn?: number /* float64 */;
  threshold_clear_crit?: number /* float64 */;
  duration?: number /* int */;
  actions?: AlertActions;
}

//////////
// source: auth.go

export interface LoginRequest {
  username: string;
  password: string;
  totp_code: string; // Optional: TOTP code if user has MFA enabled
}
export interface LoginResponse {
  token: string;
  expires_at: string;
  role: string;
  require_mfa: boolean; // True if needs TOTP step
}
export interface TOTPSecretResponse {
  secret: string; // Base32 encoded secret
  qr_code: string; // Data URL for QR code
  backup_codes: string[]; // 10 single-use backup codes
}
export const RoleAdmin = "admin"; // Full access
export const RoleOperator = "operator"; // Can launch APT commands + read all
export const RoleViewer = "viewer"; // Read-only

//////////
// source: command.go

/**
 * RemoteCommand represents any task dispatched to a remote agent.
 * module ∈ "docker" | "apt" | "systemd" | "journal"
 */
export interface RemoteCommand {
  id: string; // UUID v4
  host_id: string;
  module: string; // docker | apt | systemd | journal
  action: string; // start, stop, upgrade, logs, list, …
  target: string; // container / service name; empty for apt
  payload: string; // JSON extra args (e.g. {"working_dir": "…"})
  status: string; // pending | running | completed | failed
  output: string;
  triggered_by: string;
  audit_log_id?: number /* int64 */;
  scheduled_task_id?: string;
  created_at: string;
  started_at?: string;
  ended_at?: string;
}
export interface DockerCommandRequest {
  host_id: string;
  container_name: string;
  action: string;
  working_dir: string; // required for compose_* actions
}
export interface PendingCommand {
  id: string; // UUID
  module: string; // docker | apt | systemd | journal
  action: string; // start, stop, upgrade, logs, list, …
  target: string; // container / service name; empty for apt
  payload: string; // JSON extra args
}
export interface CommandResult {
  command_id: string; // UUID
  status: string; // running | completed | failed
  output: string;
  apt_status?: AptStatus; // Full APT status after update/upgrade
}
export interface AuditLog {
  id: number /* int64 */;
  username: string; // Who
  action: string; // What (apt_update, apt_upgrade, user_created, etc.)
  host_id: string; // On which host (nullable)
  host_name: string; // Display name (if available)
  ip_address: string; // Client IP
  details: string; // JSON payload (command output, new privileges, etc.)
  status: string; // pending, completed, failed
  created_at: string;
}

//////////
// source: docker.go

export interface DockerContainer {
  id: string;
  host_id: string;
  hostname: string; // Host's hostname for display
  container_id: string;
  name: string;
  image: string;
  image_tag: string;
  image_id: string;
  image_digest: string; // manifest sha256 (RepoDigest)
  state: string; // running, stopped, paused, etc.
  status: string;
  created: string;
  ports: string;
  labels: { [key: string]: string};
  env_vars: { [key: string]: string};
  volumes: string[];
  networks: string[];
  net_rx_bytes: number /* uint64 */;
  net_tx_bytes: number /* uint64 */;
  updated_at: string;
}
export interface DockerReport {
  host_id: string;
  containers: DockerContainer[];
  timestamp: string;
}
export interface ComposeProject {
  id: string;
  host_id: string;
  hostname: string;
  name: string;
  working_dir: string;
  config_file: string;
  services: string[];
  raw_config: string;
  updated_at: string;
}
export interface VersionComparison {
  tracker_id: string;
  docker_image: string;
  running_version: string;
  latest_version: string;
  is_up_to_date: boolean;
  update_confirmed: boolean; // true when digest comparison confirms an update (even if running version is unknown)
  container_count: number /* int */; // number of containers using this image on the host
  custom_task_id: string; // empty if monitoring-only (no auto-deployment task)
  repo_owner: string;
  repo_name: string;
  release_url: string;
  host_id: string;
  hostname: string;
}
/**
 * DockerNetwork represents a Docker network and its connected containers
 */
export interface DockerNetwork {
  id: string;
  host_id: string;
  network_id: string;
  name: string;
  driver: string; // bridge, overlay, host, none
  scope: string; // local, swarm
  container_ids: string[]; // Stored as JSONB, not queried directly
  updated_at: string;
}
export interface CVEInfo {
  id: string;
  severity: string; // Mapped from UbuntuPriority
  ubuntu_priority: string; // Raw Ubuntu priority (critical/high/medium/low/negligible)
  cvss_score: number /* float64 */; // CVSS v3 score (0 if unavailable)
  cvss_vector?: string;
  package: string;
}
export interface AptStatus {
  id: number /* int64 */;
  host_id: string;
  last_update: string;
  last_upgrade: string;
  pending_packages: number /* int */;
  package_list: string; // JSON array of package names
  security_updates: number /* int */;
  cve_list: string; // JSON array of CVEInfo
  updated_at: string;
}
/**
 * AptCVESummary aggregates CVE severity counts across all hosts.
 */
export interface AptCVESummary {
  hosts_with_critical: number /* int */;
  hosts_with_high: number /* int */;
  critical_count: number /* int */;
  high_count: number /* int */;
  medium_count: number /* int */;
  total_cve_count: number /* int */;
}
export interface AptCommandRequest {
  host_ids: string[];
  command: string;
}
export interface UUConfig {
  security_only: boolean;
  auto_reboot: boolean;
  auto_reboot_time: string; // e.g. "02:00"
  remove_unused: boolean;
}
export interface UURun {
  run_at: string;
  packages: string[];
  had_error: boolean;
  log_snippet?: string;
}
/**
 * UnattendedUpgradesStatus is the state of unattended-upgrades on a host,
 * reported by the agent on every cycle.
 */
export interface UnattendedUpgradesStatus {
  installed: boolean;
  enabled: boolean;
  reboot_required: boolean;
  config: UUConfig;
  /**
   * NewRuns contains only runs discovered since the last agent report.
   */
  new_runs: UURun[];
}
/**
 * UnattendedUpgradesDB is the persisted view returned by API endpoints.
 */
export interface UnattendedUpgradesDB {
  installed: boolean;
  enabled: boolean;
  reboot_required: boolean;
  last_run_at?: string;
  last_run_packages: number /* int */;
  config: UUConfig;
}
/**
 * UnattendedUpgradesConfigureRequest is the body for PUT /hosts/:id/apt/unattended-upgrades.
 */
export interface UnattendedUpgradesConfigureRequest {
  enabled: boolean;
  config: UUConfig;
}

//////////
// source: host.go

/**
 * HostPermission records per-host access granted to a user.
 */
export interface HostPermission {
  username: string;
  host_id: string;
  level: string; // "viewer" | "operator"
  created_at: string;
}
export interface Host {
  id: string;
  name: string; // User-defined name (e.g., "Prod Web Server")
  hostname: string; // System hostname (auto-populated by agent)
  ip_address: string;
  os: string; // Auto-populated by agent
  agent_version: string; // Agent version
  tags: string[];
  status: string; // online, offline, warning
  last_seen: string;
  created_at: string;
  updated_at: string;
  /**
   * Collectors tracks which metrics sources are active on this host (docker, smart, cpu_temp, web_logs, etc.)
   */
  collectors: { [key: string]: boolean}; // e.g., {"docker": true, "smart": false, "cpu_temp": true}
}
export interface HostRegistration {
  name: string;
  ip_address: string;
  tags: string[];
}
export interface HostUpdate {
  name?: string;
  hostname?: string;
  ip_address?: string;
  os?: string;
  agent_version?: string;
  tags?: string[];
}
export interface SystemMetrics {
  id: number /* int64 */;
  host_id: string;
  timestamp: string;
  /**
   * CPU
   */
  cpu_usage_percent: number /* float64 */;
  cpu_cores: number /* int */;
  cpu_model: string;
  cpu_temperature: number /* float64 */;
  fan_rpm: number /* float64 */;
  load_avg_1: number /* float64 */;
  load_avg_5: number /* float64 */;
  load_avg_15: number /* float64 */;
  /**
   * Memory
   */
  memory_total: number /* uint64 */;
  memory_used: number /* uint64 */;
  memory_free: number /* uint64 */;
  memory_percent: number /* float64 */;
  swap_total: number /* uint64 */;
  swap_used: number /* uint64 */;
  /**
   * Network
   */
  network_rx_bytes: number /* uint64 */;
  network_tx_bytes: number /* uint64 */;
  /**
   * System
   */
  uptime: number /* uint64 */;
  os: string;
  hostname: string;
}
/**
 * SystemMetricsSummary is a global aggregated view used for dashboard charts.
 */
export interface SystemMetricsSummary {
  timestamp: string;
  cpu_avg: number /* float64 */;
  memory_avg: number /* float64 */;
  sample_count: number /* int */;
}
export interface DiskMetrics {
  id: number /* int64 */;
  host_id: string;
  timestamp: string;
  mount_point: string;
  filesystem: string;
  size_gb: number /* float64 */;
  used_gb: number /* float64 */;
  avail_gb: number /* float64 */;
  used_percent: number /* float64 */;
  inodes_total: number /* int64 */;
  inodes_used: number /* int64 */;
  inodes_free: number /* int64 */;
  inodes_percent: number /* float64 */;
}
/**
 * DiskHealth for SMART monitoring (optional, collected if smartctl available)
 */
export interface DiskHealth {
  id: number /* int64 */;
  host_id: string;
  collected_at: string;
  device: string; // /dev/sda, /dev/nvme0n1
  model: string;
  serial_number: string;
  smart_status: string; // PASSED, FAILED, UNKNOWN
  temperature: number /* int */; // Celsius
  power_on_hours: number /* int64 */;
  power_cycles: number /* int64 */;
  realloc_sectors: number /* int */;
  pending_sectors: number /* int */;
  uncorrectable_sectors: number /* int */;
  percentage_used: number /* int */; // SSD/NVMe wear indicator
}

//////////
// source: network.go

export interface PortMapping {
  host_ip: string;
  host_port: number /* int */;
  container_port: number /* int */;
  protocol: string;
  raw: string;
}
export interface NetworkContainer {
  id: string;
  host_id: string;
  hostname: string;
  name: string;
  image: string;
  image_tag: string;
  state: string;
  status: string;
  ports: string;
  port_mappings: PortMapping[];
  labels?: { [key: string]: string};
  net_rx_bytes: number /* uint64 */;
  net_tx_bytes: number /* uint64 */;
}
export interface NetworkHost {
  id: string;
  name: string;
  hostname: string;
  ip_address: string;
  status: string;
  network_rx_bytes: number /* uint64 */;
  network_tx_bytes: number /* uint64 */;
  last_seen: string;
}
export interface NetworkSnapshot {
  hosts: NetworkHost[];
  containers: NetworkContainer[];
  updated_at: string;
}
/**
 * NetworkTopologyConfig stores persisted configuration (replaces localStorage)
 */
export interface NetworkTopologyConfig {
  id: number /* int64 */;
  root_label: string;
  root_ip: string;
  excluded_ports: number /* int */[]; // Stored as JSONB
  service_map: string; // JSON {port: name}
  host_overrides: string; // JSON
  manual_services: string; // JSON
  authelia_label: string;
  authelia_ip: string;
  internet_label: string;
  internet_ip: string;
  node_positions: string; // JSON {nodeId: {x, y}}
  root_host_id: string;
  authelia_host_id: string;
  root_port_id: string; // e.g. "80-tcp"
  authelia_port_id: string; // e.g. "9091-tcp"
  updated_at: string;
}
/**
 * TopologySnapshot is the complete network state sent via WebSocket
 */
export interface TopologySnapshot {
  hosts: NetworkHost[];
  containers: NetworkContainer[];
  config?: NetworkTopologyConfig;
  updated_at: string;
}

//////////
// source: proxmox.go

/**
 * ProxmoxConnection stores configuration for one Proxmox VE endpoint.
 * token_secret is never serialised to JSON to avoid leaks.
 */
export interface ProxmoxConnection {
  id: string;
  name: string;
  api_url: string;
  token_id: string;
  insecure_skip_verify: boolean;
  enabled: boolean;
  poll_interval_sec: number /* int */;
  last_error: string;
  last_error_at?: string;
  last_success_at?: string;
  created_at: string;
  updated_at: string;
  /**
   * Computed stats (joined, not stored)
   */
  node_count?: number /* int */;
  guest_count?: number /* int */;
}
export interface ProxmoxNode {
  id: string;
  connection_id: string;
  node_name: string;
  cpu_temp_source_host_id?: string;
  cpu_temp_source_host_name?: string;
  fan_rpm_source_host_id?: string;
  fan_rpm_source_host_name?: string;
  status: string;
  cpu_count: number /* int */;
  cpu_usage: number /* float64 */;
  mem_total: number /* int64 */;
  mem_used: number /* int64 */;
  uptime: number /* int64 */;
  pve_version: string;
  cluster_name: string;
  ip_address: string;
  last_seen_at: string;
  /**
   * Pending apt updates (polled from /nodes/{node}/apt/update)
   */
  pending_updates: number /* int */;
  security_updates: number /* int */;
  last_update_check_at?: string;
  /**
   * Computed counts
   */
  vm_count?: number /* int */;
  lxc_count?: number /* int */;
  /**
   * Detail view (populated on single-node fetch)
   */
  guests?: ProxmoxGuest[];
  storages?: ProxmoxStorage[];
  disks?: ProxmoxDisk[];
  tasks?: ProxmoxTask[];
}
export interface ProxmoxGuest {
  id: string;
  connection_id: string;
  node_name: string;
  guest_type: string; // vm | lxc
  vmid: number /* int */;
  name: string;
  status: string;
  cpu_alloc: number /* float64 */;
  cpu_usage: number /* float64 */;
  mem_alloc: number /* int64 */;
  mem_usage: number /* int64 */;
  disk_alloc: number /* int64 */;
  tags: string;
  uptime: number /* int64 */;
  last_seen_at: string;
}
export interface ProxmoxStorage {
  id: string;
  connection_id: string;
  node_name: string;
  storage_name: string;
  storage_type: string;
  total: number /* int64 */;
  used: number /* int64 */;
  avail: number /* int64 */;
  enabled: boolean;
  active: boolean;
  shared: boolean;
  last_seen_at: string;
}
/**
 * ProxmoxTask represents a single Proxmox task (from GET /nodes/{node}/tasks).
 */
export interface ProxmoxTask {
  id: string;
  connection_id: string;
  node_name: string;
  upid: string;
  task_type: string;
  status: string; // running | stopped
  user_name: string;
  start_time?: string;
  end_time?: string;
  exit_status: string; // OK | error message | ""
  object_id: string; // vmid or other Proxmox object
  last_seen_at: string;
}
/**
 * ProxmoxBackupJob represents a Proxmox backup job configuration (GET /cluster/backup).
 */
export interface ProxmoxBackupJob {
  id: string;
  connection_id: string;
  job_id: string;
  enabled: boolean;
  schedule: string;
  storage: string;
  mode: string; // snapshot | suspend | stop
  compress: string;
  vmids: string; // comma-separated VMIDs or "all"
  mail_to: string;
  last_seen_at: string;
}
/**
 * ProxmoxBackupRun stores the latest backup result per VM (derived from vzdump tasks).
 */
export interface ProxmoxBackupRun {
  id: string;
  connection_id: string;
  node_name: string;
  vmid: number /* int */;
  task_upid: string;
  status: string; // OK | error | running
  start_time?: string;
  end_time?: string;
  exit_status: string;
  last_seen_at: string;
  /**
   * Joined from proxmox_guests
   */
  guest_name?: string;
}
/**
 * ProxmoxDisk represents a physical disk in a Proxmox node (GET /nodes/{node}/disks/list).
 */
export interface ProxmoxDisk {
  id: string;
  connection_id: string;
  node_name: string;
  dev_path: string;
  model: string;
  serial: string;
  size_bytes: number /* int64 */;
  disk_type: string; // ssd | hdd | nvme | unknown
  health: string; // PASSED | FAILED | UNKNOWN
  wearout: number /* int */; // SSD wear % (100=new), -1 if N/A
  last_seen_at: string;
}
/**
 * ProxmoxConnectionRequest is the body for create/update endpoints.
 * TokenSecret is optional on update (empty means "keep existing").
 */
export interface ProxmoxConnectionRequest {
  name: string;
  api_url: string;
  token_id: string;
  token_secret: string;
  insecure_skip_verify: boolean;
  enabled: boolean;
  poll_interval_sec: number /* int */;
}
/**
 * ProxmoxSummary is returned by GET /proxmox/summary.
 */
export interface ProxmoxSummary {
  connection_count: number /* int */;
  node_count: number /* int */;
  vm_count: number /* int */;
  lxc_count: number /* int */;
  storage_total: number /* int64 */;
  storage_used: number /* int64 */;
  /**
   * Health signals (computed, read-only)
   */
  nodes_down: number /* int */;
  storage_near_full: number /* int */; // usage > 80 %
  storage_offline: number /* int */; // active=false or enabled=false
  recent_failed_tasks: number /* int */; // exit_status != 'OK' in last 24 h
}
/**
 * ProxmoxNodeMetricsSummary is a time-bucketed aggregate used for dashboard trend charts.
 * cpu_avg is expressed as a percentage (0‒100).
 */
export interface ProxmoxNodeMetricsSummary {
  timestamp: string;
  cpu_avg: number /* float64 */;
  memory_avg: number /* float64 */;
  sample_count: number /* int */;
}
/**
 * ProxmoxGuestLink maps a Proxmox guest (VM/LXC) to a ServerSupervisor host (agent).
 * Status lifecycle: suggested (auto-detected) → confirmed (validated) or ignored (dismissed).
 * MetricsSource controls which data source feeds CPU/RAM/disk in host views.
 */
export interface ProxmoxGuestLink {
  id: string;
  guest_id: string;
  host_id: string;
  status: string; // suggested | confirmed | ignored
  metrics_source: string; // auto | agent | proxmox
  created_at: string;
  updated_at: string;
  /**
   * Joined display fields (populated on list/get)
   */
  guest_name?: string;
  guest_type?: string;
  node_name?: string;
  vmid?: number /* int */;
  host_name?: string;
  host_hostname?: string;
  /**
   * Live metrics from the Proxmox guest (populated on list/get)
   */
  cpu_usage: number /* float64 */;
  mem_alloc: number /* int64 */;
  mem_usage: number /* int64 */;
}
/**
 * ProxmoxGuestLinkRequest is the body for POST /proxmox/links.
 */
export interface ProxmoxGuestLinkRequest {
  guest_id: string;
  host_id: string;
  status: string; // defaults to "confirmed"
  metrics_source: string; // defaults to "auto"
}
/**
 * ProxmoxGuestLinkUpdate is the body for PUT /proxmox/links/:id.
 */
export interface ProxmoxGuestLinkUpdate {
  status?: string;
  metrics_source?: string;
}

//////////
// source: report.go

/**
 * AgentCapabilities tracks which collectors are active on the agent
 */
export interface AgentCapabilities {
  docker: boolean; // Docker collector enabled
  apt: boolean; // APT package collector enabled
  smart: boolean; // SMART disk health enabled
  cpu_temp: boolean; // CPU temperature collector enabled
  web_logs: boolean; // Web access log parsing enabled
  systemd: boolean; // Systemd unit monitoring enabled
  journal: boolean; // Journald log collection enabled
}
/**
 * AgentReport is the full status report sent by the agent to the server
 */
export interface AgentReport {
  host_id: string;
  agent_version: string;
  capabilities?: AgentCapabilities; // Which collectors are enabled on this agent
  metrics?: SystemMetrics;
  docker?: DockerReport;
  unattended_upgrades?: UnattendedUpgradesStatus;
  web_logs?: WebLogReport;
  docker_networks?: DockerNetwork[];
  compose_projects?: ComposeProject[];
  disk_metrics?: DiskMetrics[];
  disk_health?: DiskHealth[];
  custom_tasks?: CustomTaskSummary[];
  tasks_config_yaml?: string;
  timestamp: string;
}

//////////
// source: settings.go

/**
 * SettingsUpdateRequest is the admin body for PUT /settings. Every field is
 * optional; only the ones provided (non-zero, or non-nil for SMTPTLS) are
 * persisted to the settings table.
 */
export interface SettingsUpdateRequest {
  smtp_host: string;
  smtp_port: number /* int */;
  smtp_user: string;
  smtp_pass: string;
  smtp_from: string;
  smtp_to: string;
  smtp_tls?: boolean;
  ntfy_url: string;
  github_token: string;
  metrics_retention_days: number /* int */;
  audit_retention_days: number /* int */;
}

//////////
// source: synthetic.go

/**
 * UptimeProbe configures a periodic HTTP or TCP check executed from the server.
 */
export interface UptimeProbe {
  id: string;
  name: string;
  type: string; // "http" | "tcp"
  target: string; // URL for http, host:port for tcp
  interval_sec: number /* int */;
  timeout_sec: number /* int */;
  expected_status: number /* int */; // http only
  expected_body_regex: string;
  follow_redirects: boolean;
  verify_tls: boolean;
  enabled: boolean;
  last_status: string; // up | down | unknown
  last_latency_ms?: number /* int */;
  last_status_code?: number /* int */;
  last_error?: string;
  last_checked_at?: string;
  consecutive_failures: number /* int */;
  created_at: string;
  updated_at: string;
}
/**
 * UptimeProbeRequest is the create/update body for an uptime probe. The pointer
 * fields default to true server-side when omitted (see uptimeProbeFromRequest).
 */
export interface UptimeProbeRequest {
  name: string;
  type: string;
  target: string;
  interval_sec: number /* int */;
  timeout_sec: number /* int */;
  expected_status: number /* int */;
  expected_body_regex: string;
  follow_redirects?: boolean;
  verify_tls?: boolean;
  enabled?: boolean;
}
/**
 * UptimeProbeResult is one historical execution sample for an UptimeProbe.
 */
export interface UptimeProbeResult {
  id: number /* int64 */;
  probe_id: string;
  checked_at: string;
  success: boolean;
  status_code?: number /* int */;
  latency_ms: number /* int */;
  error?: string;
}
/**
 * UptimeStats aggregates the success/failure split of a probe over a window.
 */
export interface UptimeStats {
  window_hours: number /* int */;
  total_checks: number /* int */;
  successful_checks: number /* int */;
  uptime_percent: number /* float64 */;
  avg_latency_ms: number /* float64 */;
  p95_latency_ms: number /* int */;
}
/**
 * SSLCertificate represents a monitored TLS endpoint and its last check result.
 */
export interface SSLCertificate {
  id: string;
  name: string;
  host: string;
  port: number /* int */;
  server_name?: string; // SNI override; empty = use Host
  enabled: boolean;
  last_checked_at?: string;
  valid_from?: string;
  valid_to?: string;
  issuer?: string;
  subject?: string;
  serial_number?: string;
  dns_names?: string[];
  days_remaining?: number /* int */;
  last_error?: string;
  created_at: string;
  updated_at: string;
}
/**
 * SSLCertificateRequest is the create/update body for a monitored TLS endpoint.
 * Port defaults to 443 and Enabled to true when omitted (see sslCertFromRequest).
 */
export interface SSLCertificateRequest {
  name: string;
  host: string;
  port: number /* int */;
  server_name: string;
  enabled?: boolean;
}

//////////
// source: task.go

export interface ScheduledTask {
  id: string;
  host_id: string;
  name: string;
  module: string; // apt | docker | systemd | journal | processes | custom
  action: string;
  target: string;
  payload: string; // JSON extra args
  cron_expression: string;
  enabled: boolean;
  last_run_at?: string;
  next_run_at?: string;
  last_run_status?: string; // completed | failed | nil
  last_command_id?: string;
  created_by: string;
  created_at: string;
}
/**
 * ScheduledTaskWithHost embeds ScheduledTask and adds host display name.
 */
export interface ScheduledTaskWithHost {
  ScheduledTask: ScheduledTask;
  host_name: string;
}
export interface ScheduledTaskRequest {
  name: string;
  module: string;
  action: string;
  target: string;
  payload: string;
  cron_expression: string;
  enabled: boolean;
}
/**
 * CustomTaskSummary is the lightweight representation of a custom task sent in
 * agent reports so the server can display available tasks in the UI.
 */
export interface CustomTaskSummary {
  id: string;
  name: string;
}

//////////
// source: tracker.go

export interface ReleaseTracker {
  id: string;
  name: string;
  tracker_type: string; // "git" | "docker"
  provider: string; // github, gitlab, gitea (git type only)
  repo_owner: string;
  repo_name: string;
  docker_image: string; // docker image name (docker type: required; git type: unused)
  docker_tag: string; // docker tag to monitor (docker type, e.g. "latest")
  host_id: string;
  custom_task_id: string;
  last_release_tag: string;
  latest_image_digest?: string; // manifest sha256 for docker trackers
  cooldown_hours: number /* int */;
  last_release_detected_at?: string;
  last_checked_at?: string;
  last_triggered_at?: string;
  last_error?: string;
  notify_channels: string[];
  notify_on_release: boolean;
  enabled: boolean;
  created_at: string;
  host_name?: string;
  last_execution?: ReleaseTrackerExecution;
  /**
   * Compose update mode (Watchtower-like). UpdateAction "custom" (default)
   * dispatches a tasks.yaml command; "compose" dispatches the native compose
   * module which runs pull + up -d on ComposeProject.
   */
  update_action: string;
  compose_project?: string;
  compose_service?: string; // empty = whole project
  pre_update_task_id?: string;
  post_update_task_id?: string;
  cleanup_after_update: boolean;
  healthcheck_timeout_sec: number /* int */;
  rollback_on_failure: boolean;
  registry_credentials_id?: string;
}
/**
 * ReleaseTrackerRequest is the create/update body for a release tracker — the
 * writable configuration subset of ReleaseTracker. The polling state
 * (last_release_tag, latest_image_digest, last_*_at, last_error) and the joined
 * fields (id, created_at, host_name, last_execution) are server-managed and never
 * accepted from the client.
 */
export interface ReleaseTrackerRequest {
  name: string;
  tracker_type: string;
  provider: string;
  repo_owner: string;
  repo_name: string;
  docker_image: string;
  docker_tag: string;
  host_id: string;
  custom_task_id: string;
  cooldown_hours: number /* int */;
  notify_channels: string[];
  notify_on_release: boolean;
  enabled: boolean;
  update_action: string;
  compose_project: string;
  compose_service: string;
  pre_update_task_id: string;
  post_update_task_id: string;
  cleanup_after_update: boolean;
  healthcheck_timeout_sec: number /* int */;
  rollback_on_failure: boolean;
  registry_credentials_id: string;
}
export interface ReleaseTrackerExecution {
  id: string;
  tracker_id: string;
  command_id?: string;
  tag_name: string;
  release_url: string;
  release_name: string;
  status: string;
  triggered_at: string;
  completed_at?: string;
}
/**
 * RegistryCredential stores authentication for polling private image registries.
 * Password is write-only at the API boundary (omitted from list/get responses).
 */
export interface RegistryCredential {
  id: string;
  name: string;
  registry_host: string;
  username: string;
  password?: string;
  created_at: string;
  updated_at: string;
}
/**
 * RegistryCredentialRequest is the create/update body for a registry credential —
 * the writable subset of RegistryCredential (id, created_at, updated_at are
 * server-managed). Password is required on create; an empty value on update keeps
 * the stored secret.
 */
export interface RegistryCredentialRequest {
  name: string;
  registry_host: string;
  username: string;
  password?: string;
}
/**
 * TrackableContainer is a compose-managed container discovered across hosts
 * that does not yet have a release tracker — used to pre-fill bulk creation.
 */
export interface TrackableContainer {
  host_id: string;
  host_name: string;
  image: string;
  image_tag: string;
  compose_project: string;
  compose_service: string;
}
export interface ReleaseVersionHistoryItem {
  version: string;
  name?: string;
  release_url?: string;
  published_at?: string;
}
export interface GitHubRelease {
  tag_name: string;
  name: string;
  published_at: string;
  html_url: string;
  prerelease: boolean;
  draft: boolean;
}

//////////
// source: user.go

export interface User {
  id: number /* int64 */;
  username: string;
  role: string; // admin, operator, viewer
  mfa_enabled: boolean;
  must_change_password: boolean;
  created_at: string;
}
/**
 * LoginEvent records a login attempt (success or failure) for security auditing.
 */
export interface LoginEvent {
  id: number /* int64 */;
  username: string;
  ip_address: string;
  success: boolean;
  user_agent: string;
  created_at: string;
}
/**
 * RefreshToken represents a long-lived token for re-authentication
 */
export interface RefreshToken {
  id: string;
  user_id: number /* int64 */;
  expires_at: string;
  created_at: string;
}
/**
 * APIKey allows automated access
 */
export interface APIKey {
  id: string;
  user_id: number /* int64 */;
  name: string;
  expires_at?: string;
  created_at: string;
}
/**
 * LoginStats aggregates login event counts for a time window.
 */
export interface LoginStats {
  total: number /* int */;
  failures: number /* int */;
  unique_ips: number /* int */;
}
/**
 * IPFailCount holds the number of failed logins for a single IP.
 */
export interface IPFailCount {
  ip_address: string;
  fail_count: number /* int */;
}

//////////
// source: web_logs.go

export interface WebRequest {
  timestamp: string;
  ip: string;
  method: string;
  path: string;
  status: number /* int */;
  bytes: number /* int64 */;
  user_agent: string;
  domain: string;
  category?: string;
  blocked?: boolean;
  blocked_source?: string;
  blocked_reason?: string;
  blocked_at?: string;
  blocked_until?: string;
}
export interface NPMPathHit {
  path: string;
  hits: number /* int */;
}
export interface NPMDomainStat {
  domain: string;
  hits: number /* int */;
  bytes: number /* int64 */;
  errors_4xx: number /* int */;
  errors_5xx: number /* int */;
  methods: { [key: string]: number /* int */};
  top_paths: NPMPathHit[];
}
export interface TrafficSummary {
  total_requests: number /* int */;
  total_bytes: number /* int64 */;
  errors_4xx: number /* int */;
  errors_5xx: number /* int */;
  top_domains: NPMDomainStat[];
}
export interface BotDetectionIP {
  ip: string;
  hits: number /* int */;
  unique_paths: number /* int */;
  first_seen: string;
  last_seen: string;
  category: string;
  user_agents: string[];
  requests: WebRequest[];
  blocked?: boolean;
  blocked_source?: string;
  blocked_type?: string; // "ban", "captcha", "audit", etc. (CrowdSec decision type)
  blocked_reason?: string;
  blocked_at?: string;
  blocked_until?: string;
}
export interface BotDetectionPath {
  path: string;
  category: string;
  hits: number /* int */;
}
export interface CrowdSecBlockedEntry {
  ip: string;
  type?: string; // "ban", "captcha", "audit", etc.
  reason: string;
  origin: string;
  country?: string;
  as_name?: string;
  blocked_until?: string;
}
export interface ThreatSummary {
  suspicious_requests: number /* int */;
  unique_suspicious_ips: number /* int */;
  top_suspicious_ips: BotDetectionIP[];
  top_suspicious_paths: BotDetectionPath[];
  crowdsec_total_blocked?: number /* int */;
  crowdsec_top_blocked?: CrowdSecBlockedEntry[];
}
export interface WebLogReport {
  source: string;
  traffic?: TrafficSummary;
  threats?: ThreatSummary;
  requests: WebRequest[];
  log_files_scanned: string[];
  tail_lines_per_file: number /* int */;
  total_requests: number /* int */;
  collected_at: string;
}
export interface WebLogIPTimelineRow {
  timestamp: string;
  host_id: string;
  host_name: string;
  source: string;
  ip: string;
  method: string;
  path: string;
  status: number /* int */;
  bytes: number /* int64 */;
  user_agent: string;
  domain: string;
  category: string;
  blocked?: boolean;
  blocked_source?: string;
  blocked_reason?: string;
  blocked_at?: string;
  blocked_until?: string;
}

//////////
// source: webhook.go

export interface GitWebhook {
  id: string;
  name: string;
  secret?: string; // Only included when explicitly fetched
  provider: string;
  repo_filter: string;
  branch_filter: string;
  event_filter: string;
  host_id: string;
  custom_task_id: string;
  notify_channels: string[];
  notify_on_success: boolean;
  notify_on_failure: boolean;
  enabled: boolean;
  last_triggered_at?: string;
  created_at: string;
  host_name?: string; // joined from hosts
  last_execution?: GitWebhookExecution; // most recent execution
}
/**
 * GitWebhookRequest is the create/update body for a git webhook — the writable
 * subset of GitWebhook. id, secret, last_triggered_at, created_at, host_name and
 * last_execution are server-managed and never accepted from the client.
 */
export interface GitWebhookRequest {
  name: string;
  provider: string;
  repo_filter: string;
  branch_filter: string;
  event_filter: string;
  host_id: string;
  custom_task_id: string;
  notify_channels: string[];
  notify_on_success: boolean;
  notify_on_failure: boolean;
  enabled: boolean;
}
export interface GitWebhookExecution {
  id: string;
  webhook_id: string;
  command_id?: string;
  provider: string;
  repo_name: string;
  branch: string;
  commit_sha: string;
  commit_message: string;
  pusher: string;
  status: string;
  triggered_at: string;
  completed_at?: string;
}

//////////
// source: ws.go

/**
 * DashboardHostMetrics is the lean per-host metric subset the dashboard actually
 * renders (CPU %, memory %, uptime). The full SystemMetrics carries ~20 more
 * fields (temperatures, load, swap, network, cpu model, …) consumed only by the
 * host detail view, so the dashboard snapshot — re-pushed every 10s per client —
 * ships this instead of the whole struct per host.
 */
export interface DashboardHostMetrics {
  cpu_usage_percent: number /* float64 */;
  memory_percent: number /* float64 */;
  uptime: number /* uint64 */;
}
/**
 * WSDashboardSnapshot is broadcast on the dashboard endpoint (type "dashboard").
 */
export interface WSDashboardSnapshot {
  type: string;
  hosts: Host[];
  host_metrics: { [key: string]: DashboardHostMetrics | undefined};
  version_comparisons: VersionComparison[];
  apt_pending: number /* int */;
  apt_pending_hosts: { [key: string]: number /* int */};
  disk_usage: { [key: string]: number /* float64 */};
  proxmox_nodes: ProxmoxNode[];
  proxmox_links: ProxmoxGuestLink[];
}
/**
 * WSHostSnapshot is broadcast on the host-detail endpoint (type "host_detail").
 * apt command history and per-host audit logs are intentionally absent: the
 * frontend host-detail WS consumer never read them (they live on the global Audit
 * page via REST), so shipping 50+50 rows on every metric tick was dead payload.
 */
export interface WSHostSnapshot {
  type: string;
  host?: Host;
  metrics?: SystemMetrics;
  containers: DockerContainer[];
  apt_status?: AptStatus;
  uu_status?: UnattendedUpgradesDB;
  uu_runs: UURun[];
  version_comparisons: VersionComparison[];
  proxmox_link?: ProxmoxGuestLink;
}
/**
 * WSDockerSnapshot is broadcast on the docker endpoint (type "docker").
 */
export interface WSDockerSnapshot {
  type: string;
  containers: DockerContainer[];
  compose_projects: ComposeProject[];
  version_comparisons: VersionComparison[];
}
/**
 * WSNetworkSnapshot is broadcast on the network endpoint (type "network").
 */
export interface WSNetworkSnapshot {
  type: string;
  hosts: NetworkHost[];
  containers: NetworkContainer[];
  config?: NetworkTopologyConfig;
  updated_at: string;
}
/**
 * WSAptSnapshot is broadcast on the apt endpoint (type "apt").
 */
export interface WSAptSnapshot {
  type: string;
  hosts: Host[];
  apt_statuses: { [key: string]: AptStatus | undefined};
  apt_histories: { [key: string]: RemoteCommand[]};
}
/**
 * WSCommandStreamInit is the first message sent on connect: the command's current
 * status plus any output buffered so far (empty while still running).
 */
export interface WSCommandStreamInit {
  type: string; // "cmd_stream_init"
  command_id: string;
  status: string;
  command: string;
  output: string;
}
/**
 * WSCommandStreamChunk carries one chunk of live command output (type "cmd_stream").
 */
export interface WSCommandStreamChunk {
  type: string;
  command_id: string;
  chunk: string;
}
/**
 * WSCommandStatusUpdate signals a command status transition (type
 * "cmd_status_update"); Output is set on terminal statuses (completed/failed).
 */
export interface WSCommandStatusUpdate {
  type: string;
  command_id: string;
  status: string;
  output?: string;
}
/**
 * WSAlertIncidentNotification is the nested payload of a "new_alert" message.
 */
export interface WSAlertIncidentNotification {
  id: string;
  type: string; // "alert_incident"
  rule_id: number /* int64 */;
  host_id: string;
  host_name: string;
  rule_name: string;
  metric: string;
  value: number /* float64 */;
  triggered_at: string;
  resolved_at?: string;
  browser_notify: boolean;
}
/**
 * WSNewAlertMessage is pushed when an alert incident fires (type "new_alert").
 */
export interface WSNewAlertMessage {
  type: string;
  notification: WSAlertIncidentNotification;
}
/**
 * WSAlertIncidentUpdate is a lightweight flat event (no nested notification) that
 * lets the frontend refresh its incidents list without polling (type
 * "alert_incident_update").
 */
export interface WSAlertIncidentUpdate {
  type: string;
  event: string; // "fired" | "resolved"
  rule_id: number /* int64 */;
  host_id: string;
}
/**
 * WSWebhookNotification is the nested payload of a "webhook_execution" message.
 */
export interface WSWebhookNotification {
  webhook_id: string;
  webhook_name: string;
  status: string;
  triggered_at: string;
}
/**
 * WSWebhookExecutionMessage is pushed when a git-webhook command completes
 * (type "webhook_execution").
 */
export interface WSWebhookExecutionMessage {
  type: string;
  notification: WSWebhookNotification;
}
/**
 * WSReleaseTrackerNotification is the nested payload of release-tracker messages.
 * version/release_url/release_name/label are populated only for
 * "release_tracker_detected".
 */
export interface WSReleaseTrackerNotification {
  tracker_id: string;
  tracker_name: string;
  tracker_type: string;
  version?: string;
  release_url?: string;
  release_name?: string;
  status: string;
  label?: string;
  triggered_at: string;
}
/**
 * WSReleaseTrackerMessage is pushed on release detection / execution completion
 * (type "release_tracker_detected" | "release_tracker_execution").
 */
export interface WSReleaseTrackerMessage {
  type: string;
  notification: WSReleaseTrackerNotification;
}
/**
 * WSUUNotification is the nested payload of an "unattended_upgrade" message.
 */
export interface WSUUNotification {
  id: string;
  type: string; // "unattended_upgrade"
  host_id: string;
  host_name: string;
  packages: string[];
  pkg_count: number /* int */;
  run_at: string;
  browser_notify: boolean;
  title: string;
  message: string;
}
/**
 * WSUnattendedUpgradeMessage is pushed after an unattended-upgrades run
 * (type "unattended_upgrade").
 */
export interface WSUnattendedUpgradeMessage {
  type: string;
  notification: WSUUNotification;
}
