// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// Code generated by tygo from server/internal/models. DO NOT EDIT.
// Regenerate: cd server && go run github.com/gzuidhof/tygo@v0.2.21 generate

//////////
// source: alert.go

/**
 * CommandTrigger defines a remote command to execute automatically when an alert fires.
 */
export interface CommandTrigger {
  module: string; // e.g. "processes", "journal", "docker", "systemd"
  action: string; // e.g. "list", "read", "restart"
  target?: string; // e.g. service name, container name
  payload?: string; // optional JSON payload
}
/**
 * ProxmoxMetricScope defines how a Proxmox metric should be evaluated.
 * ScopeMode can be one of: global, connection, node, storage.
 */
export interface ProxmoxMetricScope {
  scope_mode?: string;
  connection_id?: string;
  node_id?: string;
  storage_id?: string;
  guest_id?: string;
  disk_id?: string;
}
/**
 * DockerMetricScope defines how a Docker metric should be evaluated.
 * ScopeMode can be one of: host, container, compose_project.
 * HostID is always required. ContainerID or ProjectName are required for their respective modes.
 * WarnStates and CritStates are used by docker_container_state to select which container states trigger each severity.
 */
export interface DockerMetricScope {
  scope_mode: string;
  host_id: string;
  /**
   * ContainerID is the legacy single-container field, kept for rules saved
   * before multi-container selection existed. New rules are written to
   * ContainerIDs instead — see EffectiveContainerIDs for the read-time
   * migration that lets both shapes keep working unmodified.
   */
  container_id?: string; // DB UUID of docker_containers row
  container_ids?: string[]; // DB UUIDs of docker_containers rows
  project_name?: string; // compose project name
  warn_states?: string[]; // container states triggering warn
  crit_states?: string[]; // container states triggering crit
}
export type AlertSourceType = string;
export const AlertSourceAgent: AlertSourceType = "agent";
export const AlertSourceProxmox: AlertSourceType = "proxmox";
export const AlertSourceDocker: AlertSourceType = "docker";
/**
 * AlertMetricCapability describes a metric the UI can build a rule on.
 */
export interface AlertMetricCapability {
  metric: string;
  label: string;
  unit: string;
  icon: string;
  badge_class: string;
  supports_threshold: boolean;
  supports_duration: boolean;
  supports_host_filter: boolean;
  /**
   * SupportsBaselineWindow tells the frontend to render the 1h/6h/24h
   * rolling-baseline window picker (AlertRule.BaselineWindowSeconds)
   * instead of/alongside the duration field — currently only
   * bandwidth_vs_rolling_avg sets this.
   */
  supports_baseline_window?: boolean;
}
/**
 * AlertScopeOption is a selectable {id,label} scope entry (Proxmox connection,
 * node, storage, guest, disk, or a Docker host).
 */
export interface AlertScopeOption {
  id: string;
  label: string;
}
/**
 * AlertHostCapabilities is the per-host metric availability response.
 */
export interface AlertHostCapabilities {
  host_id: string;
  host_name: string;
  metrics: AlertMetricCapability[];
}
/**
 * AlertProxmoxScope groups the Proxmox scope options by kind.
 */
export interface AlertProxmoxScope {
  modes: string[];
  connections: AlertScopeOption[];
  nodes: AlertScopeOption[];
  storages: AlertScopeOption[];
  guests: AlertScopeOption[];
  disks: AlertScopeOption[];
}
/**
 * AlertSplitCapabilities is the Proxmox capabilities response (metrics + scope).
 */
export interface AlertSplitCapabilities {
  agent_metrics: AlertMetricCapability[];
  proxmox_metrics: AlertMetricCapability[];
  proxmox_scope: AlertProxmoxScope;
}
/**
 * AlertDockerScopeContainer is a container option for a Docker alert scope.
 */
export interface AlertDockerScopeContainer {
  id: string;
  name: string;
  image: string;
  state: string;
}
/**
 * AlertDockerScopeProject is a compose-project option for a Docker alert scope.
 */
export interface AlertDockerScopeProject {
  name: string;
  services: string[];
}
/**
 * AlertDockerHostScope groups a host's container + compose-project scope options.
 */
export interface AlertDockerHostScope {
  host_id: string;
  host_name: string;
  containers: AlertDockerScopeContainer[];
  projects: AlertDockerScopeProject[];
}
/**
 * AlertDockerCapabilities is the Docker capabilities response (metrics + hosts).
 */
export interface AlertDockerCapabilities {
  metrics: AlertMetricCapability[];
  hosts: AlertDockerHostScope[];
}
/**
 * AlertActions holds the consolidated notification configuration for an alert rule.
 * Stored as a single JSONB column in the database.
 */
export interface AlertActions {
  channels: string[]; // e.g. ["smtp", "ntfy", "browser"]
  smtp_to?: string; // SMTP recipient address(es)
  ntfy_topic?: string; // ntfy push notification topic
  cooldown?: number /* int */; // seconds between re-notifications (0 = no cooldown)
  command_trigger?: CommandTrigger; // optional command to run on alert
  /**
   * EscalateAfterMinutes, when > 0, re-sends the fired notification for an
   * open incident that hasn't been acknowledged, every N minutes since it
   * triggered (or since the last escalation) — see internal/alerts/engine.go.
   * 0 (default) disables escalation entirely. Unlike Cooldown, this never
   * suppresses the *first* notification; it only repeats an unacknowledged
   * one.
   */
  escalate_after_minutes?: number /* int */;
}
export interface AlertRule {
  id: number /* int64 */;
  name?: string;
  source_type?: AlertSourceType;
  host_id?: string;
  proxmox_scope?: ProxmoxMetricScope;
  docker_scope?: DockerMetricScope;
  metric: string;
  operator: string;
  threshold_warn?: number /* float64 */;
  threshold_crit?: number /* float64 */;
  threshold_clear_warn?: number /* float64 */; // hysteresis for warn
  threshold_clear_crit?: number /* float64 */; // hysteresis for crit
  duration_seconds: number /* int */;
  /**
   * BaselineWindowSeconds is the rolling-average window used by
   * bandwidth_vs_rolling_avg (one of 3600/21600/86400 = 1h/6h/24h — see
   * validateBaselineWindow in internal/services/alertrule/service.go).
   * Nil/unset for every other metric; GetMetricValue defaults to 3600 when
   * nil so it never needs to reject an old rule of a different metric.
   */
  baseline_window_seconds?: number /* int */;
  actions: AlertActions; // stored as JSONB in DB
  last_fired?: string;
  enabled: boolean;
  created_at: string;
  updated_at?: string;
  active_incident_count: number /* int */;
}
export interface AlertIncident {
  id: number /* int64 */;
  rule_id?: number /* int64 */;
  host_id: string;
  severity: string; // "warn" or "crit"
  triggered_at: string;
  resolved_at?: string;
  value: number /* float64 */;
  /**
   * CommandID is the remote_commands row a command_trigger dispatched when
   * this incident fired, if the rule has one configured. Nil otherwise.
   */
  command_id?: string;
  /**
   * AcknowledgedAt/AcknowledgedBy mark that someone is handling this incident
   * — orthogonal to ResolvedAt (see migration 087's comment). Both nil until
   * AcknowledgeIncident is called; never cleared once resolved.
   */
  acknowledged_at?: string;
  acknowledged_by?: string;
  /**
   * CorrelatedWith is the id of the host's own open status_offline/
   * heartbeat_timeout incident this one was linked to at creation time — a
   * host-down cascade (e.g. every Docker container on that host firing its
   * own incident) is still recorded per-incident but doesn't independently
   * notify or escalate (see maybeCorrelateWithHostDown/maybeEscalateIncident
   * in internal/alerts/engine.go). Nil for an uncorrelated incident, or for
   * a host-down incident itself (it's never correlated with another one).
   */
  correlated_with?: number /* int64 */;
  /**
   * Enriched post-fetch (not DB columns): Docker synthetic IDs resolution,
   * and the live status of CommandID's remote_commands row (joined at read
   * time so the frontend doesn't need a second round-trip per incident).
   */
  value_label?: string;
  link_host_id?: string;
  command_status?: string;
}
export interface NotificationItem {
  id: string;
  type: string;
  rule_id?: number /* int64 */;
  host_id: string;
  host_name: string;
  source_type?: string;
  source_label?: string;
  rule_name: string;
  metric: string;
  severity?: string;
  status?: string;
  tracker_id?: string;
  tracker_type?: string;
  release_url?: string;
  release_name?: string;
  version?: string;
  value: number /* float64 */;
  triggered_at: string;
  resolved_at?: string;
  browser_notify: boolean;
  /**
   * CurrentValue / ClearThreshold are populated only for active alert
   * incidents: the live metric value and the threshold it must cross to
   * resolve (hysteresis clear threshold, or the trigger threshold otherwise).
   */
  current_value?: number /* float64 */;
  clear_threshold?: number /* float64 */;
  operator?: string;
  /**
   * Docker synthetic ID resolution: real host to navigate to, and human state label
   */
  link_host_id?: string;
  value_label?: string;
  /**
   * CommandStatus is the remote_commands.status of the rule's command_trigger
   * dispatch for this incident (alert_incident type only), joined from
   * alert_incidents.command_id — empty when no command_trigger fired.
   */
  command_status?: string;
  /**
   * AcknowledgedAt/AcknowledgedBy mirror AlertIncident's fields (alert_incident
   * type only; always nil for a release-tracker entry).
   */
  acknowledged_at?: string;
  acknowledged_by?: string;
  /**
   * CorrelatedWith mirrors AlertIncident.CorrelatedWith (alert_incident type
   * only) — lets the UI mark a host-down cascade child without a second call.
   */
  correlated_with?: number /* int64 */;
}
/**
 * PushSubscription represents a Web Push (VAPID) subscription for a user's browser/device.
 * Stored server-side so that alert notifications can be delivered even when the app is closed.
 */
export interface PushSubscription {
  id: number /* int64 */;
  username: string;
  endpoint: string;
  p256dh: string;
  auth: string;
  user_agent?: string;
  created_at: string;
}
export interface AlertRuleCreate {
  name: string;
  enabled: boolean;
  source_type: AlertSourceType;
  host_id?: string;
  proxmox_scope?: ProxmoxMetricScope;
  docker_scope?: DockerMetricScope;
  metric: string;
  operator: string;
  threshold_warn: number /* float64 */;
  threshold_crit: number /* float64 */;
  threshold_clear_warn?: number /* float64 */;
  threshold_clear_crit?: number /* float64 */;
  duration: number /* int */;
  /**
   * BaselineWindowSeconds — see AlertRule's field doc.
   */
  baseline_window_seconds?: number /* int */;
  actions: AlertActions;
}
/**
 * AlertRuleTemplate is a reusable rule "recipe" for agent metrics — no host,
 * so ApplyAlertRuleTemplateRequest can stamp out the same rule across many
 * hosts at once instead of re-entering the same metric/thresholds/actions
 * per host (ROADMAP.md item #9). Not a live link to the rules it spawns:
 * editing or deleting a template never touches an already-created rule (same
 * "definition + independent instances" shape as runbooks/runbook_steps).
 * Docker/Proxmox-scoped rules aren't templatable in this MVP — Docker
 * scope's host_id is required per rule and Proxmox scope is cluster-level
 * already, so neither fits "apply the same recipe to N hosts."
 */
export interface AlertRuleTemplate {
  id: number /* int64 */;
  name: string;
  metric: string;
  operator: string;
  threshold_warn: number /* float64 */;
  threshold_crit: number /* float64 */;
  threshold_clear_warn?: number /* float64 */;
  threshold_clear_crit?: number /* float64 */;
  duration_seconds: number /* int */;
  /**
   * BaselineWindowSeconds — see AlertRule's field doc.
   */
  baseline_window_seconds?: number /* int */;
  actions: AlertActions;
  created_at: string;
  updated_at: string;
}
export interface AlertRuleTemplateRequest {
  name: string;
  metric: string;
  operator: string;
  threshold_warn: number /* float64 */;
  threshold_crit: number /* float64 */;
  threshold_clear_warn?: number /* float64 */;
  threshold_clear_crit?: number /* float64 */;
  duration: number /* int */;
  /**
   * BaselineWindowSeconds — see AlertRule's field doc.
   */
  baseline_window_seconds?: number /* int */;
  actions: AlertActions;
}
/**
 * ApplyAlertRuleTemplateRequest is the body of POST /alert-rule-templates/:id/apply.
 * Enabled defaults to false (zero value) — applying a template to a fleet
 * shouldn't immediately start firing everywhere before the admin has
 * reviewed the resulting per-host rules.
 */
export interface ApplyAlertRuleTemplateRequest {
  host_ids: string[];
  enabled: boolean;
}
/**
 * ApplyAlertRuleTemplateResult reports what happened per host — applying to
 * N hosts is not all-or-nothing, one host's failure shouldn't block the rest.
 */
export interface ApplyAlertRuleTemplateResult {
  created_rule_ids: number /* int64 */[];
  errors?: { [key: string]: string}; // host_id -> error message
}
export interface AlertRuleUpdate {
  name?: string;
  enabled?: boolean;
  source_type?: AlertSourceType;
  host_id?: string;
  proxmox_scope?: ProxmoxMetricScope;
  docker_scope?: DockerMetricScope;
  metric?: string;
  operator?: string;
  threshold_warn?: number /* float64 */;
  threshold_crit?: number /* float64 */;
  threshold_clear_warn?: number /* float64 */;
  threshold_clear_crit?: number /* float64 */;
  duration?: number /* int */;
  /**
   * BaselineWindowSeconds — see AlertRule's field doc. A pointer-to-pointer
   * isn't needed: nil means "leave unchanged" like every other field here,
   * and the metric using this (bandwidth_vs_rolling_avg) always requires a
   * preset value from the frontend, so there's no "explicitly clear it"
   * case to support.
   */
  baseline_window_seconds?: number /* int */;
  actions?: AlertActions;
}

//////////
// source: audit.go

/**
 * Audit log categories (ROADMAP.md item #13: per-category retention +
 * export). Low-maintenance by design — action is free text with no strict
 * enum anywhere else (any CreateAuditLog caller can pass a new string), so
 * CategorizeAuditAction buckets by a handful of known prefixes/exact matches
 * and defaults everything else to "command" rather than requiring every new
 * action string to be taught to a growing switch statement.
 */
export const AuditCategoryAlert = "alert";
/**
 * Audit log categories (ROADMAP.md item #13: per-category retention +
 * export). Low-maintenance by design — action is free text with no strict
 * enum anywhere else (any CreateAuditLog caller can pass a new string), so
 * CategorizeAuditAction buckets by a handful of known prefixes/exact matches
 * and defaults everything else to "command" rather than requiring every new
 * action string to be taught to a growing switch statement.
 */
export const AuditCategorySettings = "settings";
/**
 * Audit log categories (ROADMAP.md item #13: per-category retention +
 * export). Low-maintenance by design — action is free text with no strict
 * enum anywhere else (any CreateAuditLog caller can pass a new string), so
 * CategorizeAuditAction buckets by a handful of known prefixes/exact matches
 * and defaults everything else to "command" rather than requiring every new
 * action string to be taught to a growing switch statement.
 */
export const AuditCategoryAuth = "auth";
/**
 * Audit log categories (ROADMAP.md item #13: per-category retention +
 * export). Low-maintenance by design — action is free text with no strict
 * enum anywhere else (any CreateAuditLog caller can pass a new string), so
 * CategorizeAuditAction buckets by a handful of known prefixes/exact matches
 * and defaults everything else to "command" rather than requiring every new
 * action string to be taught to a growing switch statement.
 */
export const AuditCategoryCommand = "command";
/**
 * AuditCategory describes one bucket for the retention-settings UI and the
 * audit log browser's category filter.
 */
export interface AuditCategory {
  key: string;
  label: string;
}

//////////
// source: auth.go

export interface LoginRequest {
  username: string;
  password: string;
  totp_code: string; // Optional: TOTP code if user has MFA enabled
}
export interface LoginResponse {
  token: string;
  expires_at: string;
  role: string;
  require_mfa: boolean; // True if needs TOTP step
}
export interface TOTPSecretResponse {
  secret: string; // Base32 encoded secret
  qr_code: string; // Data URL for QR code
  backup_codes: string[]; // 10 single-use backup codes
}
/**
 * MFARequirement describes which second factors are available for a user who
 * still needs to complete an MFA step at login — the frontend uses this to
 * decide whether to show the TOTP code field, a "use your security key"
 * button, or both.
 */
export interface MFARequirement {
  totp: boolean;
  webauthn: boolean;
}
export const RoleAdmin = "admin"; // Full access
export const RoleOperator = "operator"; // Can launch APT commands + read all
export const RoleViewer = "viewer"; // Read-only

//////////
// source: backup.go

/**
 * BackupRun is one Restic backup execution — dispatched via
 * module=restic action=run_backup (manual trigger or a scheduled task) and
 * populated from the linked remote_commands row's terminal result. Never
 * contains restic/Swift/SMTP credentials.
 */
export interface BackupRun {
  id: string;
  host_id: string;
  profile?: string;
  command_id?: string;
  triggered_by?: string;
  status: string; // running | ok | warning | error
  started_at: string;
  finished_at?: string;
  duration_sec?: number /* int */;
  progress_percent?: number /* float64 */;
  files_done?: number /* int64 */;
  files_total?: number /* int64 */;
  bytes_done?: number /* int64 */;
  bytes_total?: number /* int64 */;
  snapshot_id?: string;
  snapshot_time?: string;
  repo_size_bytes?: number /* int64 */;
  error_message?: string;
  raw_summary?: string;
  created_at: string;
}
/**
 * BackupStatus is the aggregated view returned by GET .../backup: the latest
 * backup_runs row when one exists, else a fallback built from the periodic,
 * passive ResticStatus report (for hosts whose backups aren't dispatched by
 * ServerSupervisor at all).
 */
export interface BackupStatus {
  latest_run?: BackupRun;
  passive_state?: ResticStatus;
}

//////////
// source: command.go

/**
 * RemoteCommand represents any task dispatched to a remote agent.
 * module ∈ "docker" | "apt" | "systemd" | "journal"
 */
export interface RemoteCommand {
  id: string; // UUID v4
  host_id: string;
  module: string; // docker | apt | systemd | journal
  action: string; // start, stop, upgrade, logs, list, …
  target: string; // container / service name; empty for apt
  payload: string; // JSON extra args (e.g. {"working_dir": "…"})
  status: string; // pending | running | completed | failed
  output: string;
  triggered_by: string;
  audit_log_id?: number /* int64 */;
  scheduled_task_id?: string;
  runbook_execution_id?: string;
  created_at: string;
  started_at?: string;
  ended_at?: string;
}
export interface DockerCommandRequest {
  host_id: string;
  container_name: string;
  action: string;
  working_dir: string; // required for compose_* actions
}
export interface PendingCommand {
  id: string; // UUID
  module: string; // docker | apt | systemd | journal
  action: string; // start, stop, upgrade, logs, list, …
  target: string; // container / service name; empty for apt
  payload: string; // JSON extra args
}
export interface CommandResult {
  command_id: string; // UUID
  status: string; // running | completed | failed
  output: string;
  apt_status?: AptStatus; // Full APT status after update/upgrade
  /**
   * UnattendedUpgrades is a fresh CollectUnattendedUpgrades() snapshot bundled
   * into the terminal report of install_uu/toggle_uu/configure_uu/run_uu, the
   * same "fast, synchronous" pattern AptStatus uses for update/upgrade/dist-upgrade —
   * without it, the UU section only refreshes on the agent's next periodic report.
   */
  unattended_upgrades?: UnattendedUpgradesStatus;
}
/**
 * HostTimelineEvent is a single merged event in a host's activity timeline.
 * Type is one of "audit" | "command" | "incident".
 */
export interface HostTimelineEvent {
  id: string;
  type: string;
  timestamp: string;
  title: string;
  detail?: string;
  status?: string;
  severity?: string;
  module?: string;
  /**
   * Action and Target are only set for Type=="command" — they mirror
   * remote_commands.action/.target and are what the frontend's
   * resolveStructuredOutput(module, action, output) needs to render a
   * command's output through the same per-type formatting (ProcessesTable /
   * SystemdTable / ResticBackupSummaryCard) as the Commandes/Audit views,
   * instead of falling back to a raw dump.
   */
  action?: string;
  target?: string;
  /**
   * Output is the full, untruncated remote_commands.output for Type=="command"
   * (Detail above stays a short truncated summary for the table row) — the
   * structured-output parsers need the complete JSON, not a 120-char slice.
   * Empty for audit/incident-type events.
   */
  output?: string;
  /**
   * User is the acting username, straight from audit_logs.username /
   * remote_commands.triggered_by — "system" for an automated trigger
   * (scheduled task, alert rule, release tracker), same convention already
   * used elsewhere for triggered_by (e.g. AptHostCard.vue). Empty for
   * incident-type events, which have no user concept.
   */
  user?: string;
}
export interface AuditLog {
  id: number /* int64 */;
  username: string; // Who
  action: string; // What (apt_update, apt_upgrade, user_created, etc.)
  host_id: string; // On which host (nullable)
  host_name: string; // Display name (if available)
  ip_address: string; // Client IP
  details: string; // JSON payload (command output, new privileges, etc.)
  status: string; // pending, completed, failed
  created_at: string;
  /**
   * Category is computed once at write time by CategorizeAuditAction (see
   * models/audit.go) — drives per-category retention and the audit log
   * browser's filter.
   */
  category: string;
}

//////////
// source: dashboard.go

/**
 * AttentionItem is one entry in the aggregated "needs attention" feed served
 * by GET /v1/dashboard/attention — signals the backend already detects but
 * that are otherwise only visible by landing on the exact right page (a
 * suggested Proxmox link only shows on that host's detail page, an NPM host
 * with monitoring off only shows in the NPM list, ...). Mirrors the shape
 * frontend/src/composables/useAttentionCenter.ts previously computed
 * client-side from five separate list endpoints.
 */
export interface AttentionItem {
  key: string;
  label: string;
  count: number /* int */;
  to: string;
  severity: string; // "info" | "warning"
}

//////////
// source: discovery.go

/**
 * NetworkScanRequest is a subnet discovery scan request: ping-sweep every
 * usable address in an IPv4 CIDR block.
 */
export interface NetworkScanRequest {
  cidr: string;
}
/**
 * DiscoveredHost is one address's outcome from a subnet discovery scan.
 */
export interface DiscoveredHost {
  ip_address: string;
  responded: boolean;
  latency_ms?: number /* int */;
  already_registered: boolean;
  existing_host_id?: string;
  existing_host_name?: string;
}

//////////
// source: docker.go

export interface DockerContainer {
  id: string;
  host_id: string;
  hostname: string; // Host's ServerSupervisor display name (hosts.name) — not the raw agent-reported system hostname
  container_id: string;
  name: string;
  image: string;
  image_tag: string;
  image_id: string;
  image_digest: string; // manifest sha256 (RepoDigest)
  state: string; // running, stopped, paused, etc.
  status: string;
  created: string;
  ports: string;
  labels: { [key: string]: string};
  env_vars: { [key: string]: string};
  volumes: string[];
  networks: string[];
  /**
   * IPAddresses are the container's Docker-assigned addresses across its
   * attached networks. Reported by the agent (which needs them locally to
   * attribute container traffic in the network-flow collector — see
   * agent/internal/collector/container_ips.go) and accepted here as container
   * metadata; not persisted, same as Labels/EnvVars/Volumes above.
   */
  ip_addresses: string[];
  net_rx_bytes: number /* uint64 */;
  net_tx_bytes: number /* uint64 */;
  updated_at: string;
}
export interface DockerReport {
  host_id: string;
  containers: DockerContainer[];
  timestamp: string;
}
export interface ComposeProject {
  id: string;
  host_id: string;
  hostname: string; // Host's ServerSupervisor display name (hosts.name), same convention as DockerContainer.Hostname
  name: string;
  working_dir: string;
  config_file: string;
  services: string[];
  raw_config: string;
  updated_at: string;
}
/**
 * DockerImageRef is a normalized (image, tag) pair — the cache key of the
 * ambient image-version engine and the unit of work of its refresh job.
 */
export interface DockerImageRef {
  image: string;
  image_tag: string;
}
/**
 * DockerImageVersion is one row of the docker_image_versions cache: the latest
 * digest a registry published for an (image, tag), refreshed on a slow ticker
 * by internal/services/dockerversions. It is the single source of truth for
 * "is there something newer upstream" — both the WS version badges and the
 * release-tracker poller read it instead of calling a registry themselves.
 */
export interface DockerImageVersion {
  image: string;
  image_tag: string;
  registry: string;
  latest_digest: string;
  latest_tag: string;
  registry_credentials_id?: string;
  checked_at?: string;
  last_error?: string;
}
/**
 * Version comparison statuses, computed server-side so the host Docker tab and
 * the global Docker page can't drift on how they classify the same row.
 */
export const VersionStatusUpToDate = "up_to_date";
/**
 * Version comparison statuses, computed server-side so the host Docker tab and
 * the global Docker page can't drift on how they classify the same row.
 */
export const VersionStatusUpdateAvailable = "update_available";
/**
 * Version comparison statuses, computed server-side so the host Docker tab and
 * the global Docker page can't drift on how they classify the same row.
 */
export const VersionStatusUnknown = "unknown";
export interface VersionComparison {
  tracker_id: string;
  docker_image: string;
  image_tag: string; // container tag this row describes; empty on tracker-aggregated rows
  running_version: string;
  latest_version: string;
  status: string; // up_to_date | update_available | unknown
  is_up_to_date: boolean;
  update_confirmed: boolean; // true when digest comparison confirms an update (even if running version is unknown)
  container_count: number /* int */; // number of containers using this image on the host
  custom_task_id: string; // empty if monitoring-only (no auto-deployment task)
  repo_owner: string;
  repo_name: string;
  release_url: string;
  host_id: string;
  hostname: string;
  /**
   * LastError explains an "unknown" status coming from the ambient engine
   * (private registry with no matching credential, registry unreachable, …).
   * Always empty on tracker-derived rows, which surface their own error on
   * the tracker itself.
   */
  last_error?: string;
}
/**
 * DockerNetwork represents a Docker network and its connected containers
 */
export interface DockerNetwork {
  id: string;
  host_id: string;
  network_id: string;
  name: string;
  driver: string; // bridge, overlay, host, none
  scope: string; // local, swarm
  container_ids: string[]; // Stored as JSONB, not queried directly
  updated_at: string;
}
export interface CVEInfo {
  id: string;
  severity: string; // Mapped from UbuntuPriority
  ubuntu_priority: string; // Raw Ubuntu priority (critical/high/medium/low/negligible)
  cvss_score: number /* float64 */; // CVSS v3 score (0 if unavailable)
  cvss_vector?: string;
  package: string;
}
export interface AptStatus {
  id: number /* int64 */;
  host_id: string;
  last_update: string;
  last_upgrade: string;
  pending_packages: number /* int */;
  package_list: string; // JSON array of package names
  security_updates: number /* int */;
  cve_list: string; // JSON array of CVEInfo
  updated_at: string;
  /**
   * CVEUpdatedAt is when security_updates/cve_list were last actually
   * refreshed by the CVE-enriched pass — nil until the first one ever runs
   * for this host. Distinct from UpdatedAt, which also bumps on the faster
   * pending-packages-only path (UpsertAptPendingPackages) that never
   * touches CVE data — lets a consumer tell "package count is fresh" apart
   * from "CVE detail is fresh".
   */
  cve_updated_at?: string;
}
/**
 * AptCVESummary aggregates CVE severity counts across all hosts.
 */
export interface AptCVESummary {
  hosts_with_critical: number /* int */;
  hosts_with_high: number /* int */;
  critical_count: number /* int */;
  high_count: number /* int */;
  medium_count: number /* int */;
  total_cve_count: number /* int */;
}
export interface AptCommandRequest {
  host_ids: string[];
  command: string;
}
export interface UUConfig {
  security_only: boolean;
  auto_reboot: boolean;
  auto_reboot_time: string; // e.g. "02:00"
  remove_unused: boolean;
}
export interface UURun {
  run_at: string;
  packages: string[];
  had_error: boolean;
  log_snippet?: string;
}
/**
 * UnattendedUpgradesStatus is the state of unattended-upgrades on a host,
 * reported by the agent on every cycle.
 */
export interface UnattendedUpgradesStatus {
  installed: boolean;
  enabled: boolean;
  reboot_required: boolean;
  config: UUConfig;
  /**
   * NewRuns contains only runs discovered since the last agent report.
   */
  new_runs: UURun[];
}
/**
 * UnattendedUpgradesDB is the persisted view returned by API endpoints.
 */
export interface UnattendedUpgradesDB {
  installed: boolean;
  enabled: boolean;
  reboot_required: boolean;
  last_run_at?: string;
  last_run_packages: number /* int */;
  config: UUConfig;
}
/**
 * UnattendedUpgradesConfigureRequest is the body for PUT /hosts/:id/apt/unattended-upgrades.
 */
export interface UnattendedUpgradesConfigureRequest {
  enabled: boolean;
  config: UUConfig;
}

//////////
// source: host.go

/**
 * HostPermission records per-host access granted to a user.
 */
export interface HostPermission {
  username: string;
  host_id: string;
  level: string; // "viewer" | "operator"
  created_at: string;
}
export interface Host {
  id: string;
  name: string; // User-defined name (e.g., "Prod Web Server")
  hostname: string; // System hostname (auto-populated by agent)
  ip_address: string;
  os: string; // Auto-populated by agent
  agent_version: string; // Agent version
  tags: string[];
  status: string; // online, offline, warning
  last_seen: string;
  created_at: string;
  updated_at: string;
  /**
   * Collectors tracks which metrics sources are active on this host (docker, smart, cpu_temp, web_logs, etc.)
   */
  collectors: { [key: string]: boolean}; // e.g., {"docker": true, "smart": false, "cpu_temp": true}
  /**
   * Diagnostics is the agent's own last self-check of its config against
   * reality (e.g. collect_restic: true but resticconf missing) — see
   * DiagnosticIssue. Empty when nothing's wrong, or before the first report.
   */
  diagnostics: DiagnosticIssue[];
}
export interface HostRegistration {
  name: string;
  ip_address: string;
  tags: string[];
}
export interface HostUpdate {
  name?: string;
  hostname?: string;
  ip_address?: string;
  os?: string;
  agent_version?: string;
  tags?: string[];
}
export interface SystemMetrics {
  id: number /* int64 */;
  host_id: string;
  timestamp: string;
  /**
   * CPU
   */
  cpu_usage_percent: number /* float64 */;
  cpu_cores: number /* int */;
  cpu_model: string;
  cpu_temperature: number /* float64 */;
  fan_rpm: number /* float64 */;
  load_avg_1: number /* float64 */;
  load_avg_5: number /* float64 */;
  load_avg_15: number /* float64 */;
  /**
   * Memory
   */
  memory_total: number /* uint64 */;
  memory_used: number /* uint64 */;
  memory_free: number /* uint64 */;
  memory_percent: number /* float64 */;
  swap_total: number /* uint64 */;
  swap_used: number /* uint64 */;
  /**
   * Network
   */
  network_rx_bytes: number /* uint64 */;
  network_tx_bytes: number /* uint64 */;
  /**
   * System
   */
  uptime: number /* uint64 */;
  os: string;
  hostname: string;
}
/**
 * SystemMetricsSummary is a global aggregated view used for dashboard charts.
 */
export interface SystemMetricsSummary {
  timestamp: string;
  cpu_avg: number /* float64 */;
  memory_avg: number /* float64 */;
  sample_count: number /* int */;
}
export interface DiskMetrics {
  id: number /* int64 */;
  host_id: string;
  timestamp: string;
  mount_point: string;
  filesystem: string;
  size_gb: number /* float64 */;
  used_gb: number /* float64 */;
  avail_gb: number /* float64 */;
  used_percent: number /* float64 */;
  inodes_total: number /* int64 */;
  inodes_used: number /* int64 */;
  inodes_free: number /* int64 */;
  inodes_percent: number /* float64 */;
  /**
   * ForecastDaysUntilFull is a linear-trend extrapolation over the last 30
   * days of used_percent samples (nil when the mount point isn't filling up,
   * or there isn't at least 7 days of history to trust a trend from).
   */
  forecast_days_until_full?: number /* float64 */;
}
/**
 * DiskHealth for SMART monitoring (optional, collected if smartctl available)
 */
export interface DiskHealth {
  id: number /* int64 */;
  host_id: string;
  collected_at: string;
  device: string; // /dev/sda, /dev/nvme0n1
  model: string;
  serial_number: string;
  smart_status: string; // PASSED, FAILED, UNKNOWN
  temperature: number /* int */; // Celsius
  power_on_hours: number /* int64 */;
  power_cycles: number /* int64 */;
  realloc_sectors: number /* int */;
  pending_sectors: number /* int */;
  uncorrectable_sectors: number /* int */;
  percentage_used: number /* int */; // SSD/NVMe wear indicator
}

//////////
// source: host_exposure.go

/**
 * HostExposedDomain is one NPM domain name that routes to a specific host
 * (matched by npm_proxy_hosts.forward_host == host.ip_address), enriched with
 * aggregated web-log traffic for that one domain over the requested window.
 * One row per domain name, not per NPM proxy host record: an NPM proxy host
 * can carry several domain-name aliases pointing at the same target, and
 * each alias gets its own real per-domain traffic figures (an NPM proxy host
 * entry isn't itself a traffic-bearing unit — domains are). The traffic rows
 * are looked up by domain, not host_id: they are collected by whichever
 * agent parses the reverse-proxy's access logs (typically the NPM host
 * itself), which is usually a different host than the backend this domain
 * forwards to.
 */
export interface HostExposedDomain {
  proxy_host_id: string;
  connection_id: string;
  connection_name: string;
  domain_name: string;
  forward_port: number /* int */;
  ssl_enabled: boolean;
  npm_enabled: boolean;
  requests: number /* int64 */;
  bytes: number /* int64 */;
  errors_4xx: number /* int64 */;
  errors_5xx: number /* int64 */;
  suspicious_requests: number /* int64 */;
  blocked_requests: number /* int64 */;
}
/**
 * HostExposure is the compute-on-read correlation result for one host: every
 * NPM domain that forwards to it (matched by IP) plus aggregated web-log
 * traffic for those domains over the requested window. Nothing here is
 * persisted — it is recomputed from npm_proxy_hosts + web_log_requests on
 * every request.
 */
export interface HostExposure {
  host_id: string;
  ip_address: string;
  since: string;
  domains: HostExposedDomain[];
  total_requests: number /* int64 */;
  total_suspicious_requests: number /* int64 */;
  total_blocked_requests: number /* int64 */;
}

//////////
// source: maintenance.go

/**
 * MaintenanceWindow suppresses alert notifications for a host (HostID set)
 * or every host (HostID nil, a global window) between StartsAt and EndsAt.
 * The alert engine (internal/alerts) checks for an active window before
 * evaluating an evaluation target and silently resolves any already-open
 * incident without notifying, exactly like a disabled rule — see
 * internal/alerts/engine.go and internal/database/db_maintenance.go's
 * IsHostInMaintenance.
 */
export interface MaintenanceWindow {
  id: string;
  host_id?: string; // nil = applies to every host
  host_name?: string;
  reason: string;
  starts_at: string;
  ends_at: string;
  created_by: string;
  created_at: string;
}
export interface MaintenanceWindowRequest {
  reason: string;
  starts_at: string;
  ends_at: string;
}

//////////
// source: network.go

export interface PortMapping {
  host_ip: string;
  host_port: number /* int */;
  container_port: number /* int */;
  protocol: string;
  raw: string;
}
export interface NetworkContainer {
  id: string;
  host_id: string;
  hostname: string;
  name: string;
  image: string;
  image_tag: string;
  state: string;
  status: string;
  ports: string;
  port_mappings: PortMapping[];
  labels?: { [key: string]: string};
  net_rx_bytes: number /* uint64 */;
  net_tx_bytes: number /* uint64 */;
}
export interface NetworkHost {
  id: string;
  name: string;
  hostname: string;
  ip_address: string;
  status: string;
  network_rx_bytes: number /* uint64 */;
  network_tx_bytes: number /* uint64 */;
  last_seen: string;
}
export interface NetworkSnapshot {
  hosts: NetworkHost[];
  containers: NetworkContainer[];
  updated_at: string;
}
/**
 * NetworkTopologyConfig stores persisted configuration (replaces localStorage)
 */
export interface NetworkTopologyConfig {
  id: number /* int64 */;
  root_label: string;
  root_ip: string;
  excluded_ports: number /* int */[]; // Stored as JSONB
  service_map: string; // JSON {port: name}
  host_overrides: string; // JSON array of {hostId, ports} entries
  manual_services: string; // JSON
  authelia_label: string;
  authelia_ip: string;
  internet_label: string;
  internet_ip: string;
  node_positions: string; // JSON {nodeId: {x, y}}
  root_host_id: string;
  authelia_host_id: string;
  root_port_id: string; // e.g. "80-tcp"
  authelia_port_id: string; // e.g. "9091-tcp"
  updated_at: string;
}
/**
 * TopologySnapshot is the complete network state sent via WebSocket
 */
export interface TopologySnapshot {
  hosts: NetworkHost[];
  containers: NetworkContainer[];
  config?: NetworkTopologyConfig;
  updated_at: string;
}
/**
 * NetworkProxmoxGuestIP is a Proxmox VM/LXC guest with its live-fetched IP
 * addresses, correlated with a ServerSupervisor Host when a confirmed
 * proxmox_guest_links entry exists.
 */
export interface NetworkProxmoxGuestIP {
  guest_id: string;
  name: string;
  node: string;
  guest_type: string; // "vm" | "lxc"
  vmid: number /* int */;
  status: string;
  ip_addresses: string[];
  host_id?: string;
  host_name?: string;
}
/**
 * NetworkNPMEntry is an Nginx Proxy Manager proxy host entry, correlated by
 * IP with a ServerSupervisor Host or a Proxmox guest when possible.
 */
export interface NetworkNPMEntry {
  proxy_host_id: number /* int */;
  domain_names: string[];
  forward_host: string;
  forward_port: number /* int */;
  matched_type?: string; // "host" | "proxmox_guest"
  matched_id?: string;
  matched_name?: string;
}
/**
 * NetworkIPInventory is the combined, real-time (non-persisted) IP inventory
 * shown on the Network page's cards view.
 */
export interface NetworkIPInventory {
  proxmox_guests: NetworkProxmoxGuestIP[];
  npm_hosts: NetworkNPMEntry[];
}

//////////
// source: network_flows.go

/**
 * NetworkFlowsReport is the agent-reported "top talkers" block for one report
 * cycle: the busiest remote peers this host talked to, derived from conntrack
 * accounting and aggregated agent-side into a bounded top-N + "others" bucket
 * (see agent/internal/collector/network_flows.go). Mirrors
 * agent/internal/collector.NetworkFlowsReport — kept in its own file rather
 * than network.go, which already covers the unrelated logical-topology domain
 * (server/internal/networkview).
 */
export interface NetworkFlowsReport {
  /**
   * Available is false when the host can't provide per-connection byte
   * counters (nf_conntrack not loaded, accounting disabled, non-Linux, or
   * collection disabled in agent.yaml) — never an error, a capability flag.
   */
  available: boolean;
  /**
   * Reason is an actionable message when Available is false.
   */
  reason?: string;
  top_talkers?: NetworkFlowTalker[];
  others?: NetworkFlowBucket;
  total_flows: number /* int */;
  collected_at: string;
}
/**
 * NetworkFlowTalker is one aggregated remote peer for a report cycle.
 * RxBytes/TxBytes/Packets are deltas since the previous cycle, not conntrack's
 * own cumulative counters — see agent/internal/collector/network_flows.go's
 * per-cycle delta tracking. This is why server-side history aggregation must
 * SUM() these values per time_bucket, not MAX()-MIN() like system_metrics'
 * truly-cumulative network_rx_bytes/network_tx_bytes.
 */
export interface NetworkFlowTalker {
  remote_ip: string;
  remote_port: number /* int */;
  protocol: string; // "tcp" | "udp"
  direction: string; // "inbound" | "outbound"
  /**
   * ProcessName/PID are best-effort (socket→inode→pid via /proc), empty/0
   * when attribution failed — never treated as a collection error. For a
   * process inside a container the host's /proc can't see the socket at all,
   * so ProcessName instead carries the agent's "conteneur: <name>" fallback
   * (PID stays 0 — a container PID is meaningless outside its namespace).
   */
  process_name?: string;
  pid?: number /* int */;
  /**
   * ServerName is the TLS SNI hostname observed on an outbound flow. Only
   * ever populated when the agent's optional, off-by-default L7 capture is
   * enabled (network_flows_l7_capture, needs CAP_NET_RAW); empty otherwise,
   * in which case the frontend falls back to its own well-known-port guess.
   */
  server_name?: string;
  rx_bytes: number /* uint64 */;
  tx_bytes: number /* uint64 */;
  packets: number /* uint64 */;
  connections: number /* int */;
}
/**
 * NetworkFlowBucket aggregates every talker beyond the agent's top-N cutoff.
 */
export interface NetworkFlowBucket {
  connections: number /* int */;
  rx_bytes: number /* uint64 */;
  tx_bytes: number /* uint64 */;
}
/**
 * NetworkFlowMetric is one persisted row in network_flow_metrics: either a
 * named talker (IsOthers=false) or the single per-cycle "others" rollup
 * (IsOthers=true, RemoteIP/RemotePort/Protocol/Direction/ProcessName/PID all
 * zero-valued).
 */
export interface NetworkFlowMetric {
  id: number /* int64 */;
  host_id: string;
  timestamp: string;
  is_others: boolean;
  remote_ip?: string;
  remote_port?: number /* int */;
  protocol?: string;
  direction?: string;
  process_name?: string;
  pid?: number /* int */;
  server_name?: string;
  rx_bytes: number /* uint64 */;
  tx_bytes: number /* uint64 */;
  packets: number /* uint64 */;
  connections: number /* int */;
}
/**
 * NetworkFlowSummaryPoint is one time-bucketed point of a host's total tracked
 * bandwidth (all talkers summed), used for the overview chart.
 */
export interface NetworkFlowSummaryPoint {
  timestamp: string;
  rx_bytes: number /* uint64 */;
  tx_bytes: number /* uint64 */;
}

//////////
// source: npm.go

/**
 * NPMConnection holds credentials and state for one Nginx Proxy Manager instance.
 * secret is never serialised to JSON to avoid leaks; it is retrieved only by the
 * poller and the test-connection endpoint.
 */
export interface NPMConnection {
  id: string;
  name: string;
  api_url: string;
  identity: string;
  host_id?: string;
  enabled: boolean;
  poll_interval_sec: number /* int */;
  last_error?: string;
  last_error_at?: string;
  last_success_at?: string;
  proxy_host_count: number /* int */;
  created_at: string;
  updated_at: string;
}
/**
 * NPMConnectionRequest is the create/update payload. Secret is optional on update
 * (empty value = keep existing). HostID is optional (nullable).
 */
export interface NPMConnectionRequest {
  name: string;
  api_url: string;
  identity: string;
  secret: string;
  host_id?: string;
  enabled?: boolean;
  poll_interval_sec: number /* int */;
}
/**
 * NPMProxyHost is one proxy-host entry imported from NPM.
 * uptime_probe_id and ssl_certificate_id are SET NULL when the linked resource is
 * deleted, so the next import can recreate them.
 * monitoring_enabled is the master switch; the sub-flags only take effect when it is true.
 */
export interface NPMProxyHost {
  id: string;
  connection_id: string;
  npm_id: number /* int */;
  domain_names: string[];
  forward_host: string;
  forward_port: number /* int */;
  ssl_enabled: boolean;
  npm_enabled: boolean;
  monitoring_enabled: boolean;
  uptime_monitoring_enabled: boolean;
  ssl_monitoring_enabled: boolean;
  uptime_probe_id?: string;
  ssl_certificate_id?: string;
  last_seen_at: string;
  created_at: string;
  updated_at: string;
}
/**
 * NPMProxyHostEnriched is NPMProxyHost enriched with connection name and live
 * status from the linked uptime probe and SSL certificate. Returned by the
 * global proxy-host list endpoint.
 */
export interface NPMProxyHostEnriched {
  NPMProxyHost: NPMProxyHost;
  connection_name: string;
  uptime_status?: string;
  uptime_last_latency_ms?: number /* int */;
  ssl_days_remaining?: number /* int */;
}
/**
 * NPMProxyHostUpdateRequest is the PATCH body for toggling monitoring flags.
 * All fields are optional; only the provided ones are applied.
 */
export interface NPMProxyHostUpdateRequest {
  monitoring_enabled?: boolean;
  uptime_monitoring_enabled?: boolean;
  ssl_monitoring_enabled?: boolean;
}
/**
 * NPMProxyHostPreview combines live NPM proxy-host data with its import status
 * in ServerSupervisor. Returned by the preview endpoint; nothing is written to DB.
 */
export interface NPMProxyHostPreview {
  npm_id: number /* int */;
  domain_names: string[];
  forward_host: string;
  forward_port: number /* int */;
  ssl_enabled: boolean;
  npm_enabled: boolean;
  already_imported: boolean;
  uptime_probe_id?: string;
  ssl_certificate_id?: string;
}

//////////
// source: oidc.go

/**
 * OIDCStatusResponse is returned to public callers (such as LoginView.vue)
 * so the UI knows whether to display the SSO button and with what label.
 */
export interface OIDCStatusResponse {
  enabled: boolean;
  display_name: string;
  allow_local_login: boolean;
}
/**
 * OIDCAuthState represents a pending authorization session before callback.
 */
export interface OIDCAuthState {
  state_id: string;
  nonce: string;
  code_verifier: string;
  redirect_url: string;
  created_at: string;
  expires_at: string;
}
/**
 * OIDCTokenClaims represents the claims extracted from an ID token.
 */
export interface OIDCTokenClaims {
  sub: string;
  email: string;
  email_verified: boolean;
  preferred_username: string;
  name: string;
  groups: string[];
  roles: string[];
}

//////////
// source: proxmox.go

/**
 * ProxmoxConnection stores configuration for one Proxmox VE endpoint.
 * token_secret is never serialised to JSON to avoid leaks.
 */
export interface ProxmoxConnection {
  id: string;
  name: string;
  api_url: string;
  token_id: string;
  insecure_skip_verify: boolean;
  enabled: boolean;
  poll_interval_sec: number /* int */;
  last_error: string;
  last_error_at?: string;
  last_success_at?: string;
  created_at: string;
  updated_at: string;
  /**
   * PVEUsername identifies which PVE user account the console feature logs
   * in as (e.g. "root@pam") — not itself secret, shown like TokenID. The
   * password never leaves the database; see ProxmoxConnectionRequest and
   * database.GetProxmoxConsoleCredentials. Console (LXC termproxy) needs a
   * real user ticket, not the API token used for everything else — PVE's
   * vncwebsocket upgrade endpoint doesn't accept token auth.
   */
  pve_username?: string;
  /**
   * ConsoleConfigured reports whether console credentials are set, without
   * ever exposing them — computed by the DB layer (pve_username <> '' AND
   * pve_password <> '').
   */
  console_configured: boolean;
  /**
   * Computed stats (joined, not stored)
   */
  node_count?: number /* int */;
  guest_count?: number /* int */;
}
export interface ProxmoxNode {
  id: string;
  connection_id: string;
  node_name: string;
  cpu_temp_source_host_id?: string;
  cpu_temp_source_host_name?: string;
  fan_rpm_source_host_id?: string;
  fan_rpm_source_host_name?: string;
  status: string;
  cpu_count: number /* int */;
  cpu_usage: number /* float64 */;
  mem_total: number /* int64 */;
  mem_used: number /* int64 */;
  uptime: number /* int64 */;
  pve_version: string;
  cluster_name: string;
  ip_address: string;
  last_seen_at: string;
  /**
   * Pending apt updates (polled from /nodes/{node}/apt/update)
   */
  pending_updates: number /* int */;
  security_updates: number /* int */;
  last_update_check_at?: string;
  /**
   * Computed counts
   */
  vm_count?: number /* int */;
  lxc_count?: number /* int */;
  /**
   * Detail view (populated on single-node fetch)
   */
  guests?: ProxmoxGuest[];
  storages?: ProxmoxStorage[];
  disks?: ProxmoxDisk[];
  tasks?: ProxmoxTask[];
}
export interface ProxmoxGuest {
  id: string;
  connection_id: string;
  node_name: string;
  guest_type: string; // vm | lxc
  vmid: number /* int */;
  name: string;
  status: string;
  cpu_alloc: number /* float64 */;
  cpu_usage: number /* float64 */;
  mem_alloc: number /* int64 */;
  mem_usage: number /* int64 */;
  disk_alloc: number /* int64 */;
  disk_usage: number /* int64 */;
  tags: string;
  uptime: number /* int64 */;
  last_seen_at: string;
}
export interface ProxmoxStorage {
  id: string;
  connection_id: string;
  node_name: string;
  storage_name: string;
  storage_type: string;
  total: number /* int64 */;
  used: number /* int64 */;
  avail: number /* int64 */;
  enabled: boolean;
  active: boolean;
  shared: boolean;
  last_seen_at: string;
}
/**
 * ProxmoxTask represents a single Proxmox task (from GET /nodes/{node}/tasks).
 */
export interface ProxmoxTask {
  id: string;
  connection_id: string;
  node_name: string;
  upid: string;
  task_type: string;
  status: string; // running | stopped
  user_name: string;
  start_time?: string;
  end_time?: string;
  exit_status: string; // OK | error message | ""
  object_id: string; // vmid or other Proxmox object
  last_seen_at: string;
}
/**
 * ProxmoxBackupJob represents a Proxmox backup job configuration (GET /cluster/backup).
 */
export interface ProxmoxBackupJob {
  id: string;
  connection_id: string;
  job_id: string;
  enabled: boolean;
  schedule: string;
  storage: string;
  mode: string; // snapshot | suspend | stop
  compress: string;
  vmids: string; // comma-separated VMIDs or "all"
  mail_to: string;
  last_seen_at: string;
}
/**
 * ProxmoxBackupRun stores the latest backup result per VM (derived from vzdump tasks).
 */
export interface ProxmoxBackupRun {
  id: string;
  connection_id: string;
  node_name: string;
  vmid: number /* int */;
  task_upid: string;
  status: string; // OK | error | running
  start_time?: string;
  end_time?: string;
  exit_status: string;
  last_seen_at: string;
  /**
   * Joined from proxmox_guests
   */
  guest_name?: string;
}
/**
 * ProxmoxDisk represents a physical disk in a Proxmox node (GET /nodes/{node}/disks/list).
 */
export interface ProxmoxDisk {
  id: string;
  connection_id: string;
  node_name: string;
  dev_path: string;
  model: string;
  serial: string;
  size_bytes: number /* int64 */;
  disk_type: string; // ssd | hdd | nvme | unknown
  health: string; // PASSED | FAILED | UNKNOWN
  wearout: number /* int */; // SSD wear % (100=new), -1 if N/A
  last_seen_at: string;
}
/**
 * ProxmoxConnectionRequest is the body for create/update endpoints.
 * TokenSecret is optional on update (empty means "keep existing").
 */
export interface ProxmoxConnectionRequest {
  name: string;
  api_url: string;
  token_id: string;
  token_secret: string;
  insecure_skip_verify: boolean;
  enabled: boolean;
  poll_interval_sec: number /* int */;
  /**
   * PVEUsername/PVEPassword are optional PVE user credentials (e.g.
   * "root@pam") used only to open an interactive LXC console — PVE
   * requires a real user ticket for that endpoint, not an API token. Empty
   * PVEPassword on update means "keep existing", same semantics as
   * TokenSecret.
   */
  pve_username: string;
  pve_password: string;
}
/**
 * ProxmoxTestResult is returned by the connection test endpoints
 * (POST /proxmox/instances/test and /proxmox/instances/:id/test). Console
 * fields are only meaningful when ConsoleConfigured is true — PVE login
 * success only proves the credentials are valid, not that the account has
 * the VM.Console privilege needed on a specific guest (that can only be
 * checked by actually opening a console).
 */
export interface ProxmoxTestResult {
  success: boolean;
  error?: string;
  console_configured: boolean;
  console_ok?: boolean;
  console_error?: string;
}
/**
 * ProxmoxSummary is returned by GET /proxmox/summary.
 */
export interface ProxmoxSummary {
  connection_count: number /* int */;
  node_count: number /* int */;
  vm_count: number /* int */;
  lxc_count: number /* int */;
  storage_total: number /* int64 */;
  storage_used: number /* int64 */;
  /**
   * Health signals (computed, read-only)
   */
  nodes_down: number /* int */;
  storage_near_full: number /* int */; // usage > 80 %
  storage_offline: number /* int */; // active=false or enabled=false
  recent_failed_tasks: number /* int */; // exit_status != 'OK' in last 24 h
  /**
   * IDs of the proxmox_nodes rows behind each health signal above, so the
   * frontend can filter/highlight the node table instead of showing an
   * inactionable count. Node-level (NodesDown) is a direct proxmox_nodes
   * query; the other three join through proxmox_storages/proxmox_tasks on
   * (connection_id, node_name) since those tables don't carry a node ID.
   */
  nodes_down_ids?: string[];
  storage_near_full_node_ids?: string[];
  storage_offline_node_ids?: string[];
  failed_task_node_ids?: string[];
}
/**
 * ProxmoxNodeMetricsSummary is a time-bucketed aggregate used for dashboard trend charts.
 * cpu_avg is expressed as a percentage (0‒100).
 */
export interface ProxmoxNodeMetricsSummary {
  timestamp: string;
  cpu_avg: number /* float64 */;
  memory_avg: number /* float64 */;
  sample_count: number /* int */;
}
/**
 * ProxmoxGuestLink maps a Proxmox guest (VM/LXC) to a ServerSupervisor host (agent).
 * Status lifecycle: suggested (auto-detected) → confirmed (validated) or ignored (dismissed).
 * MetricsSource controls which data source feeds CPU/RAM/disk in host views.
 */
export interface ProxmoxGuestLink {
  id: string;
  guest_id: string;
  host_id: string;
  status: string; // suggested | confirmed | ignored
  metrics_source: string; // auto | agent | proxmox
  created_at: string;
  updated_at: string;
  /**
   * Joined display fields (populated on list/get)
   */
  guest_name?: string;
  guest_type?: string;
  node_name?: string;
  vmid?: number /* int */;
  host_name?: string;
  host_hostname?: string;
  /**
   * Live metrics from the Proxmox guest (populated on list/get)
   */
  cpu_alloc: number /* float64 */;
  cpu_usage: number /* float64 */;
  mem_alloc: number /* int64 */;
  mem_usage: number /* int64 */;
  disk_alloc: number /* int64 */;
  disk_usage: number /* int64 */;
}
/**
 * ProxmoxGuestLinkRequest is the body for POST /proxmox/links.
 */
export interface ProxmoxGuestLinkRequest {
  guest_id: string;
  host_id: string;
  status: string; // defaults to "confirmed"
  metrics_source: string; // defaults to "auto"
}
/**
 * ProxmoxGuestLinkUpdate is the body for PUT /proxmox/links/:id.
 */
export interface ProxmoxGuestLinkUpdate {
  status?: string;
  metrics_source?: string;
}

//////////
// source: report.go

/**
 * AgentCapabilities tracks which collectors are active on the agent
 */
export interface AgentCapabilities {
  docker: boolean; // Docker collector enabled
  apt: boolean; // APT package collector enabled
  smart: boolean; // SMART disk health enabled
  cpu_temp: boolean; // CPU temperature collector enabled
  web_logs: boolean; // Web access log parsing enabled
  systemd: boolean; // Systemd unit monitoring enabled
  journal: boolean; // Journald log collection enabled
  restic: boolean; // Restic backup collector enabled
  /**
   * NetworkFlows only reflects whether the collector ran, not whether the
   * kernel could actually provide byte counters — see NetworkFlowsReport.Available.
   */
  network_flows: boolean;
}
/**
 * DiagnosticIssue mirrors agent/internal/collector.DiagnosticIssue — one
 * config-vs-reality mismatch found by the agent's CheckConfig (e.g.
 * collect_restic: true with a resticconf path that doesn't exist). Severity
 * is "error" (the collector will produce zero data) or "warning" (partially
 * degraded).
 */
export interface DiagnosticIssue {
  collector: string;
  severity: string;
  message: string;
}
/**
 * ResticStatus mirrors agent/internal/collector.ResticStatus — the periodic,
 * passive snapshot of Restic's state. Never contains resticconf content or
 * resolved credential values.
 */
export interface ResticStatus {
  installed: boolean;
  last_run_at?: string;
  last_status?: string;
  duration_sec?: number /* int */;
  files_new?: number /* int */;
  files_changed?: number /* int */;
  bytes_added?: number /* int64 */;
  snapshot_id?: string;
  repo_size_bytes?: number /* int64 */;
  error_message?: string;
  source: string;
}
/**
 * AgentReport is the full status report sent by the agent to the server
 */
export interface AgentReport {
  host_id: string;
  agent_version: string;
  capabilities?: AgentCapabilities; // Which collectors are enabled on this agent
  diagnostics: DiagnosticIssue[]; // Config-vs-reality mismatches found by the agent — always sent (even empty) so a fixed issue clears server-side
  metrics?: SystemMetrics;
  docker?: DockerReport;
  unattended_upgrades?: UnattendedUpgradesStatus;
  /**
   * AptStatus mirrors CommandResult.AptStatus's shape and purpose, but for a
   * periodic report that caught a new unattended-upgrades run rather than a
   * live-dispatched apt command — see agent/internal/reporter's AptStatus doc.
   */
  apt_status?: AptStatus;
  web_logs?: WebLogReport;
  docker_networks?: DockerNetwork[];
  compose_projects?: ComposeProject[];
  disk_metrics?: DiskMetrics[];
  disk_health?: DiskHealth[];
  custom_tasks?: CustomTaskSummary[];
  tasks_config_yaml?: string;
  restic?: ResticStatus;
  restic_profiles?: string[];
  restic_groups?: string[];
  network_flows?: NetworkFlowsReport;
  timestamp: string;
}

//////////
// source: runbook.go

export interface Runbook {
  id: string;
  name: string;
  description: string;
  created_at: string;
  updated_at: string;
  steps: RunbookStep[];
}
export interface RunbookStep {
  id: string;
  runbook_id: string;
  position: number /* int */;
  host_id: string;
  module: string;
  action: string;
  target: string;
  payload: string;
  continue_on_failure: boolean;
}
/**
 * RunbookExecution is one run of a runbook, advancing one step at a time as
 * each step's remote_commands row reaches a terminal state.
 */
export interface RunbookExecution {
  id: string;
  runbook_id: string;
  status: string; // running | completed | failed
  current_step_position: number /* int */;
  triggered_by: string;
  started_at: string;
  completed_at?: string;
  runbook_name?: string;
  steps?: RunbookExecutionStep[];
}
/**
 * RunbookExecutionStep is one step's definition joined with the outcome of
 * the remote_commands row it dispatched (empty Status/CommandID if this step
 * hasn't been reached yet).
 */
export interface RunbookExecutionStep {
  position: number /* int */;
  host_id: string;
  module: string;
  action: string;
  target: string;
  command_id?: string;
  status?: string;
  output?: string;
}
export interface RunbookStepCreate {
  host_id: string;
  module: string;
  action: string;
  target: string;
  payload: string;
  continue_on_failure: boolean;
}
export interface RunbookCreate {
  name: string;
  description: string;
  steps: RunbookStepCreate[];
}
export interface RunbookUpdate {
  name?: string;
  description?: string;
  steps?: RunbookStepCreate[];
}

//////////
// source: settings.go

/**
 * SettingsUpdateRequest is the admin body for PUT /settings. Every field is
 * optional; only the ones provided (non-zero, or non-nil for SMTPTLS and the
 * threat-detection weights) are persisted to the settings table. The threat
 * weights use *float64 rather than float64 because 0 is a legitimate value
 * for a weight (e.g. "ignore 2xx entirely") and must be distinguishable from
 * "not provided" — same reasoning as SMTPTLS being a *bool.
 */
export interface SettingsUpdateRequest {
  smtp_host: string;
  smtp_port: number /* int */;
  smtp_user: string;
  smtp_pass: string;
  smtp_from: string;
  smtp_to: string;
  smtp_tls?: boolean;
  ntfy_url: string;
  github_token: string;
  metrics_retention_days: number /* int */;
  audit_retention_days: number /* int */;
  /**
   * AuditRetentionDaysByCategory, when non-nil, replaces the whole map
   * (not a per-key merge) — same semantics as the rest of this struct's
   * "send what you mean the new state to be" fields. A category omitted
   * here falls back to AuditRetentionDays. Keys are models.AuditCategories'
   * Key values; an unknown key or a non-positive value is dropped, not
   * rejected — see Service.Update.
   */
  audit_retention_days_by_category?: { [key: string]: number /* int */};
  threat_weight_wordpress?: number /* float64 */;
  threat_weight_adminpanel?: number /* float64 */;
  threat_weight_pathtraversal?: number /* float64 */;
  threat_weight_knownscanner?: number /* float64 */;
  threat_weight_suspiciousmethod?: number /* float64 */;
  threat_weight_status_2xx?: number /* float64 */;
  threat_weight_status_3xx?: number /* float64 */;
  threat_weight_status_404?: number /* float64 */;
  threat_weight_status_4xx?: number /* float64 */;
  threat_weight_status_5xx?: number /* float64 */;
  threat_weight_breadth?: number /* float64 */;
  threat_weight_hits?: number /* float64 */;
  threat_threshold_medium?: number /* float64 */;
  threat_threshold_high?: number /* float64 */;
  threat_threshold_critical?: number /* float64 */;
}

//////////
// source: synthetic.go

/**
 * UptimeProbe configures a periodic HTTP, TCP or ICMP check executed from the server.
 */
export interface UptimeProbe {
  id: string;
  name: string;
  type: string; // "http" | "tcp" | "icmp"
  target: string; // URL for http, host:port for tcp, hostname/IP for icmp
  interval_sec: number /* int */;
  timeout_sec: number /* int */;
  expected_status: number /* int */; // http only
  expected_body_regex: string;
  follow_redirects: boolean;
  verify_tls: boolean;
  enabled: boolean;
  last_status: string; // up | down | unknown
  last_latency_ms?: number /* int */;
  last_status_code?: number /* int */;
  last_error?: string;
  last_checked_at?: string;
  consecutive_failures: number /* int */;
  created_at: string;
  updated_at: string;
  /**
   * NPMProxyHostID/Domain are set when this probe was created (and is still
   * referenced) by an NPM proxy host's monitoring toggle — see
   * npm.Service.UpdateProxyHostMonitoring. Deleting a probe with this set
   * silently desyncs that proxy host's toggle state (the FK is ON DELETE
   * SET NULL, not RESTRICT), so callers should warn before deleting.
   */
  npm_proxy_host_id?: string;
  npm_proxy_host_domain?: string;
}
/**
 * UptimeProbeRequest is the create/update body for an uptime probe. The pointer
 * fields default to true server-side when omitted (see uptimeProbeFromRequest).
 */
export interface UptimeProbeRequest {
  name: string;
  type: string;
  target: string;
  interval_sec: number /* int */;
  timeout_sec: number /* int */;
  expected_status: number /* int */;
  expected_body_regex: string;
  follow_redirects?: boolean;
  verify_tls?: boolean;
  enabled?: boolean;
}
/**
 * UptimeProbeResult is one historical execution sample for an UptimeProbe.
 */
export interface UptimeProbeResult {
  id: number /* int64 */;
  probe_id: string;
  checked_at: string;
  success: boolean;
  status_code?: number /* int */;
  latency_ms: number /* int */;
  error?: string;
}
/**
 * UptimeStats aggregates the success/failure split of a probe over a window.
 */
export interface UptimeStats {
  window_hours: number /* int */;
  total_checks: number /* int */;
  successful_checks: number /* int */;
  uptime_percent: number /* float64 */;
  avg_latency_ms: number /* float64 */;
  p95_latency_ms: number /* int */;
}
/**
 * UptimeHistoryBucket is one fixed-width time slice of a probe's results over a
 * selected window, used to render the availability bar and latency chart at a
 * resolution proportional to the selected window (1h/24h/7j/30j) instead of a
 * fixed "last N checks" that only ever reflects the most recent few minutes.
 */
export interface UptimeHistoryBucket {
  bucket_start: string;
  total_checks: number /* int */;
  up_checks: number /* int */;
  down_checks: number /* int */;
  avg_latency_ms: number /* float64 */;
}
/**
 * SSLCertificate represents a monitored TLS endpoint and its last check result.
 */
export interface SSLCertificate {
  id: string;
  name: string;
  host: string;
  port: number /* int */;
  server_name?: string; // SNI override; empty = use Host
  enabled: boolean;
  last_checked_at?: string;
  valid_from?: string;
  valid_to?: string;
  issuer?: string;
  subject?: string;
  serial_number?: string;
  dns_names?: string[];
  days_remaining?: number /* int */;
  last_error?: string;
  created_at: string;
  updated_at: string;
  /**
   * NPMProxyHostID/Domain — see the identical UptimeProbe fields' comment.
   */
  npm_proxy_host_id?: string;
  npm_proxy_host_domain?: string;
}
/**
 * SSLCertificateRequest is the create/update body for a monitored TLS endpoint.
 * Port defaults to 443 and Enabled to true when omitted (see sslCertFromRequest).
 */
export interface SSLCertificateRequest {
  name: string;
  host: string;
  port: number /* int */;
  server_name: string;
  enabled?: boolean;
}
/**
 * SSLCertificateEvent records one observed certificate version for a monitored
 * endpoint. A new row is written whenever the serial_number changes, giving a
 * full renewal timeline. detected_at is the first time this serial was seen.
 */
export interface SSLCertificateEvent {
  id: number /* int64 */;
  certificate_id: string;
  serial_number: string;
  valid_from?: string;
  valid_to?: string;
  issuer?: string;
  subject?: string;
  detected_at: string;
}

//////////
// source: task.go

export interface ScheduledTask {
  id: string;
  host_id: string;
  name: string;
  module: string; // apt | docker | systemd | journal | processes | custom
  action: string;
  target: string;
  payload: string; // JSON extra args
  cron_expression: string;
  enabled: boolean;
  last_run_at?: string;
  next_run_at?: string;
  last_run_status?: string; // completed | failed | nil
  last_command_id?: string;
  created_by: string;
  created_at: string;
}
/**
 * ScheduledTaskWithHost embeds ScheduledTask and adds host display name.
 */
export interface ScheduledTaskWithHost {
  ScheduledTask: ScheduledTask;
  host_name: string;
}
export interface ScheduledTaskRequest {
  name: string;
  module: string;
  /**
   * Not binding:"required" — the "custom" module ignores Action entirely
   * (the agent only looks up Target in tasks.yaml), so it's validated
   * conditionally in scheduledtask.validate() instead of unconditionally here.
   */
  action: string;
  target: string;
  payload: string;
  cron_expression: string;
  enabled: boolean;
}
/**
 * CustomTaskSummary is the lightweight representation of a custom task sent in
 * agent reports so the server can display available tasks in the UI.
 */
export interface CustomTaskSummary {
  id: string;
  name: string;
}

//////////
// source: tracker.go

export interface ReleaseTracker {
  id: string;
  name: string;
  tracker_type: string; // "git" | "docker"
  provider: string; // github, gitlab, gitea (git type only)
  repo_owner: string;
  repo_name: string;
  docker_image: string; // docker image name (docker type: required; git type: unused)
  docker_tag: string; // docker tag to monitor (docker type, e.g. "latest")
  host_id: string;
  custom_task_id: string;
  last_release_tag: string;
  latest_image_digest?: string; // manifest sha256 for docker trackers
  cooldown_hours: number /* int */;
  last_release_detected_at?: string;
  last_checked_at?: string;
  last_triggered_at?: string;
  last_error?: string;
  notify_channels: string[];
  notify_on_release: boolean;
  enabled: boolean;
  created_at: string;
  host_name?: string;
  last_execution?: ReleaseTrackerExecution;
  /**
   * Compose update mode (Watchtower-like). UpdateAction "custom" (default)
   * dispatches a tasks.yaml command; "compose" dispatches the native compose
   * module which runs pull + up -d on ComposeProject.
   */
  update_action: string;
  compose_project?: string;
  compose_service?: string; // empty = whole project
  pre_update_task_id?: string;
  post_update_task_id?: string;
  cleanup_after_update: boolean;
  healthcheck_timeout_sec: number /* int */;
  rollback_on_failure: boolean;
  registry_credentials_id?: string;
  /**
   * ReconcileDrift: when true, the poller re-dispatches pull+up if the
   * actually-deployed container drifts from this tracker's last-recorded
   * digest even though the registry itself hasn't moved (see poller.go's
   * checkComposeDrift). False (default) means drift is only surfaced via
   * DriftDetected, never auto-corrected.
   */
  reconcile_drift: boolean;
  /**
   * DriftDetected is computed on read (never stored): true when the
   * actually-deployed digest no longer matches LatestImageDigest. Always
   * false for non-compose trackers or ones with no digest recorded yet.
   */
  drift_detected?: boolean;
}
/**
 * ReleaseTrackerRequest is the create/update body for a release tracker — the
 * writable configuration subset of ReleaseTracker. The polling state
 * (last_release_tag, latest_image_digest, last_*_at, last_error) and the joined
 * fields (id, created_at, host_name, last_execution) are server-managed and never
 * accepted from the client.
 */
export interface ReleaseTrackerRequest {
  name: string;
  tracker_type: string;
  provider: string;
  repo_owner: string;
  repo_name: string;
  docker_image: string;
  docker_tag: string;
  host_id: string;
  custom_task_id: string;
  cooldown_hours: number /* int */;
  notify_channels: string[];
  notify_on_release: boolean;
  enabled: boolean;
  update_action: string;
  compose_project: string;
  compose_service: string;
  pre_update_task_id: string;
  post_update_task_id: string;
  cleanup_after_update: boolean;
  healthcheck_timeout_sec: number /* int */;
  rollback_on_failure: boolean;
  registry_credentials_id: string;
  reconcile_drift: boolean;
}
export interface ReleaseTrackerExecution {
  id: string;
  tracker_id: string;
  command_id?: string;
  tag_name: string;
  release_url: string;
  release_name: string;
  status: string;
  triggered_at: string;
  completed_at?: string;
  /**
   * HostID/HostName are the tracker's target host at query time (joined from
   * release_trackers.host_id, not stored per-execution) — empty for a
   * monitor-only tracker with no host_id.
   */
  host_id?: string;
  host_name?: string;
  /**
   * AlertsAfterCount is the number of alert incidents that fired on the
   * tracker's target host within 15 minutes after this execution started —
   * a cheap "did this deployment just break something" signal. Always 0 for
   * trackers with no host_id (monitor-only).
   */
  alerts_after_count: number /* int */;
}
/**
 * RegistryCredential stores authentication for polling private image registries.
 * Password is write-only at the API boundary (omitted from list/get responses).
 */
export interface RegistryCredential {
  id: string;
  name: string;
  registry_host: string;
  username: string;
  password?: string;
  created_at: string;
  updated_at: string;
}
/**
 * RegistryCredentialRequest is the create/update body for a registry credential —
 * the writable subset of RegistryCredential (id, created_at, updated_at are
 * server-managed). Password is required on create; an empty value on update keeps
 * the stored secret.
 */
export interface RegistryCredentialRequest {
  name: string;
  registry_host: string;
  username: string;
  password?: string;
}
/**
 * TrackableContainer is a running container discovered across hosts, used both
 * to pre-fill bulk creation (ListTrackableContainers: compose-managed and not
 * yet tracked — the "activer la mise à jour auto" flow, which can only auto-update
 * what compose owns) and to back the single-tracker container picker
 * (ListPickableContainers: every running container, tracked or not, compose or
 * not — a manual tracker only needs an image ref, so the compose restriction
 * would hide legitimate targets). ContainerName/Tracked are populated by the
 * picker query only; they stay zero-valued in the bulk-create listing.
 */
export interface TrackableContainer {
  host_id: string;
  host_name: string;
  image: string;
  image_tag: string;
  compose_project: string;
  compose_service: string;
  container_name?: string;
  tracked?: boolean;
}
export interface ReleaseVersionHistoryItem {
  version: string;
  name?: string;
  release_url?: string;
  published_at?: string;
}
export interface GitHubRelease {
  tag_name: string;
  name: string;
  published_at: string;
  html_url: string;
  prerelease: boolean;
  draft: boolean;
}

//////////
// source: user.go

export interface User {
  id: number /* int64 */;
  username: string;
  role: string; // admin, operator, viewer
  auth_provider: string; // local, oidc
  oidc_sub?: string;
  email?: string;
  mfa_enabled: boolean;
  must_change_password: boolean;
  created_at: string;
}
/**
 * LoginEvent records a login attempt (success or failure) for security auditing.
 */
export interface LoginEvent {
  id: number /* int64 */;
  username: string;
  ip_address: string;
  success: boolean;
  user_agent: string;
  created_at: string;
}
/**
 * RefreshToken represents a long-lived token for re-authentication
 */
export interface RefreshToken {
  id: string;
  user_id: number /* int64 */;
  expires_at: string;
  created_at: string;
}
/**
 * APIKey allows automated access
 */
export interface APIKey {
  id: string;
  user_id: number /* int64 */;
  name: string;
  expires_at?: string;
  created_at: string;
}
/**
 * LoginStats aggregates login event counts for a time window.
 */
export interface LoginStats {
  total: number /* int */;
  failures: number /* int */;
  unique_ips: number /* int */;
}
/**
 * IPFailCount holds the number of failed logins for a single IP.
 */
export interface IPFailCount {
  ip_address: string;
  fail_count: number /* int */;
}

//////////
// source: web_logs.go

export interface WebRequest {
  timestamp: string;
  ip: string;
  method: string;
  path: string;
  status: number /* int */;
  bytes: number /* int64 */;
  user_agent: string;
  domain: string;
  /**
   * Category is empty on the wire from the agent — internal/threatdetect
   * fills it in server-side (via ClassifyRequests) right after decode,
   * before the report is persisted.
   */
  category?: string;
  blocked?: boolean;
  blocked_source?: string;
  blocked_reason?: string;
  blocked_at?: string;
  blocked_until?: string;
}
export interface NPMPathHit {
  path: string;
  hits: number /* int */;
}
export interface NPMDomainStat {
  domain: string;
  hits: number /* int */;
  bytes: number /* int64 */;
  errors_4xx: number /* int */;
  errors_5xx: number /* int */;
  methods: { [key: string]: number /* int */};
  top_paths: NPMPathHit[];
}
export interface TrafficSummary {
  total_requests: number /* int */;
  total_bytes: number /* int64 */;
  errors_4xx: number /* int */;
  errors_5xx: number /* int */;
  top_domains: NPMDomainStat[];
}
export interface CrowdSecBlockedEntry {
  ip: string;
  type?: string; // "ban", "captcha", "audit", etc.
  reason: string;
  origin: string;
  country?: string;
  as_name?: string;
  blocked_until?: string;
}
/**
 * ThreatSummary carries only what the agent itself can observe — the local
 * CrowdSec correlation. Suspicious-request classification and counts are
 * computed server-side (see internal/threatdetect) from the raw Requests
 * below, not reported by the agent.
 */
export interface ThreatSummary {
  crowdsec_total_blocked?: number /* int */;
  crowdsec_top_blocked?: CrowdSecBlockedEntry[];
}
export interface WebLogReport {
  source: string;
  traffic?: TrafficSummary;
  threats?: ThreatSummary;
  requests: WebRequest[];
  log_files_scanned: string[];
  tail_lines_per_file: number /* int */;
  total_requests: number /* int */;
  collected_at: string;
}
export interface WebLogIPTimelineRow {
  timestamp: string;
  host_id: string;
  host_name: string;
  source: string;
  ip: string;
  method: string;
  path: string;
  status: number /* int */;
  bytes: number /* int64 */;
  user_agent: string;
  domain: string;
  category: string;
  blocked?: boolean;
  blocked_source?: string;
  blocked_reason?: string;
  blocked_at?: string;
  blocked_until?: string;
}

//////////
// source: webauthn.go

/**
 * WebAuthnCredential is a registered passkey/security key for a user — an
 * additional MFA factor alongside TOTP. Credential holds the full go-webauthn
 * record (public key, sign counter, flags, attestation) needed to run a login
 * ceremony; it's never serialized to the client (json:"-"), only Name/dates are.
 */
export interface WebAuthnCredential {
  id: string;
  name: string;
  created_at: string;
  last_used_at?: string;
}

//////////
// source: webhook.go

export interface GitWebhook {
  id: string;
  name: string;
  secret?: string; // Only included when explicitly fetched
  provider: string;
  repo_filter: string;
  branch_filter: string;
  event_filter: string;
  host_id: string;
  custom_task_id: string;
  notify_channels: string[];
  notify_on_success: boolean;
  notify_on_failure: boolean;
  enabled: boolean;
  last_triggered_at?: string;
  created_at: string;
  host_name?: string; // joined from hosts
  last_execution?: GitWebhookExecution; // most recent execution
}
/**
 * GitWebhookRequest is the create/update body for a git webhook — the writable
 * subset of GitWebhook. id, secret, last_triggered_at, created_at, host_name and
 * last_execution are server-managed and never accepted from the client.
 */
export interface GitWebhookRequest {
  name: string;
  provider: string;
  repo_filter: string;
  branch_filter: string;
  event_filter: string;
  host_id: string;
  custom_task_id: string;
  notify_channels: string[];
  notify_on_success: boolean;
  notify_on_failure: boolean;
  enabled: boolean;
}
export interface GitWebhookExecution {
  id: string;
  webhook_id: string;
  command_id?: string;
  provider: string;
  repo_name: string;
  branch: string;
  commit_sha: string;
  commit_message: string;
  pusher: string;
  status: string;
  triggered_at: string;
  completed_at?: string;
  /**
   * RawPayload is the provider's raw JSON delivery body, truncated to a
   * bounded size (see gitwebhook.maxStoredPayloadBytes) — kept for debugging
   * "why didn't this trigger", not as an unbounded audit log.
   */
  raw_payload?: string;
}

//////////
// source: ws.go

/**
 * DashboardHostMetrics is the lean per-host metric subset the dashboard actually
 * renders (CPU %, memory %, uptime). The full SystemMetrics carries ~20 more
 * fields (temperatures, load, swap, network, cpu model, …) consumed only by the
 * host detail view, so the dashboard snapshot — re-pushed every 10s per client —
 * ships this instead of the whole struct per host.
 */
export interface DashboardHostMetrics {
  cpu_usage_percent: number /* float64 */;
  memory_percent: number /* float64 */;
  uptime: number /* uint64 */;
}
/**
 * WSDashboardSnapshot is broadcast on the dashboard endpoint (type "dashboard").
 */
export interface WSDashboardSnapshot {
  type: string;
  hosts: Host[];
  host_metrics: { [key: string]: DashboardHostMetrics | undefined};
  version_comparisons: VersionComparison[];
  apt_pending: number /* int */;
  apt_pending_hosts: { [key: string]: number /* int */};
  disk_usage: { [key: string]: number /* float64 */};
  proxmox_nodes: ProxmoxNode[];
  proxmox_links: ProxmoxGuestLink[];
}
/**
 * WSHostSnapshot is broadcast on the host-detail endpoint (type "host_detail").
 * apt command history and per-host audit logs are intentionally absent: the
 * frontend host-detail WS consumer never read them (they live on the global Audit
 * page via REST), so shipping 50+50 rows on every metric tick was dead payload.
 */
export interface WSHostSnapshot {
  type: string;
  host?: Host;
  metrics?: SystemMetrics;
  containers: DockerContainer[];
  apt_status?: AptStatus;
  uu_status?: UnattendedUpgradesDB;
  uu_runs: UURun[];
  version_comparisons: VersionComparison[];
  proxmox_link?: ProxmoxGuestLink;
}
/**
 * WSDockerSnapshot is broadcast on the docker endpoint (type "docker").
 */
export interface WSDockerSnapshot {
  type: string;
  containers: DockerContainer[];
  compose_projects: ComposeProject[];
  version_comparisons: VersionComparison[];
}
/**
 * WSNetworkSnapshot is broadcast on the network endpoint (type "network").
 */
export interface WSNetworkSnapshot {
  type: string;
  hosts: NetworkHost[];
  containers: NetworkContainer[];
  config?: NetworkTopologyConfig;
  updated_at: string;
}
/**
 * WSAptSnapshot is broadcast on the apt endpoint (type "apt").
 */
export interface WSAptSnapshot {
  type: string;
  hosts: Host[];
  apt_statuses: { [key: string]: AptStatus | undefined};
  apt_histories: { [key: string]: RemoteCommand[]};
  uu_statuses: { [key: string]: UnattendedUpgradesDB | undefined};
  /**
   * LatestAgentVersion is the currently resolved latest agent release (same
   * source as GetHostComplete's latest_agent_version) — surfaced here too so
   * the fleet-wide /apt page can flag out-of-date agents without a separate
   * per-host request for every host.
   */
  latest_agent_version: string;
}
/**
 * WSCommandStreamInit is the first message sent on connect: the command's current
 * status plus any output buffered so far (empty while still running).
 */
export interface WSCommandStreamInit {
  type: string; // "cmd_stream_init"
  command_id: string;
  status: string;
  command: string;
  output: string;
}
/**
 * WSCommandStreamChunk carries one chunk of live command output (type "cmd_stream").
 */
export interface WSCommandStreamChunk {
  type: string;
  command_id: string;
  chunk: string;
}
/**
 * WSCommandStatusUpdate signals a command status transition (type
 * "cmd_status_update"); Output is set on terminal statuses (completed/failed).
 */
export interface WSCommandStatusUpdate {
  type: string;
  command_id: string;
  status: string;
  output?: string;
}
/**
 * ===== Proxmox console (GET /api/v1/ws/proxmox/console/:guest_id) =====
 * Unlike CommandStream, this endpoint is bidirectional: raw text frames sent
 * by the browser are keystrokes/paste data, forwarded byte-for-byte to the
 * PVE shell. WSConsoleResize is the one exception — a JSON control message
 * distinguished from keystroke data by unmarshaling successfully with
 * type=="resize" (an ordinary shell input essentially never does). PVE's own
 * termproxy wire framing ("0:LEN:DATA" / "1:COLS:ROWS:" / "2") is entirely an
 * implementation detail of proxmoxclient.TermSession — this endpoint never
 * speaks it to the browser.
 */
export interface WSConsoleResize {
  type: string; // "resize"
  cols: number /* int */;
  rows: number /* int */;
}
/**
 * WSConsoleError is sent once, right before the connection is closed, when
 * the console session couldn't be opened (bad guest/permission/PVE error).
 */
export interface WSConsoleError {
  type: string; // "console_error"
  error: string;
}
/**
 * WSAlertIncidentNotification is the nested payload of a "new_alert" message.
 */
export interface WSAlertIncidentNotification {
  id: string;
  type: string; // "alert_incident"
  rule_id: number /* int64 */;
  host_id: string;
  host_name: string;
  rule_name: string;
  metric: string;
  value: number /* float64 */;
  triggered_at: string;
  resolved_at?: string;
  browser_notify: boolean;
}
/**
 * WSNewAlertMessage is pushed when an alert incident fires (type "new_alert").
 */
export interface WSNewAlertMessage {
  type: string;
  notification: WSAlertIncidentNotification;
}
/**
 * WSAlertIncidentUpdate is a lightweight flat event (no nested notification) that
 * lets the frontend refresh its incidents list without polling (type
 * "alert_incident_update").
 */
export interface WSAlertIncidentUpdate {
  type: string;
  event: string; // "fired" | "resolved"
  rule_id: number /* int64 */;
  host_id: string;
}
/**
 * WSWebhookNotification is the nested payload of a "webhook_execution" message.
 */
export interface WSWebhookNotification {
  webhook_id: string;
  webhook_name: string;
  status: string;
  triggered_at: string;
}
/**
 * WSWebhookExecutionMessage is pushed when a git-webhook command completes
 * (type "webhook_execution").
 */
export interface WSWebhookExecutionMessage {
  type: string;
  notification: WSWebhookNotification;
}
/**
 * WSBackupNotification is the nested payload of a "backup_run" message.
 */
export interface WSBackupNotification {
  host_id: string;
  status: string;
  triggered_at: string;
}
/**
 * WSBackupRunMessage is pushed when a restic run_backup command fails
 * (type "backup_run").
 */
export interface WSBackupRunMessage {
  type: string;
  notification: WSBackupNotification;
}
/**
 * WSReleaseTrackerNotification is the nested payload of release-tracker messages.
 * version/release_url/release_name/label are populated only for
 * "release_tracker_detected".
 */
export interface WSReleaseTrackerNotification {
  tracker_id: string;
  tracker_name: string;
  tracker_type: string;
  version?: string;
  release_url?: string;
  release_name?: string;
  status: string;
  label?: string;
  triggered_at: string;
}
/**
 * WSReleaseTrackerMessage is pushed on release detection / execution completion
 * (type "release_tracker_detected" | "release_tracker_execution").
 */
export interface WSReleaseTrackerMessage {
  type: string;
  notification: WSReleaseTrackerNotification;
}
/**
 * WSUUNotification is the nested payload of an "unattended_upgrade" message.
 */
export interface WSUUNotification {
  id: string;
  type: string; // "unattended_upgrade"
  host_id: string;
  host_name: string;
  packages: string[];
  pkg_count: number /* int */;
  run_at: string;
  browser_notify: boolean;
  title: string;
  message: string;
}
/**
 * WSUnattendedUpgradeMessage is pushed after an unattended-upgrades run
 * (type "unattended_upgrade").
 */
export interface WSUnattendedUpgradeMessage {
  type: string;
  notification: WSUUNotification;
}
