version: "2"

linters:
  enable:
    - errcheck
    - ineffassign
    - staticcheck
    - govet
    - unused
    - gosimple

severity:
  default-severity: error
  rules:
    - linters:
        - ineffassign
      text: "ineffectual assignment"
      severity: warning
    - linters:
        - staticcheck
      text: "SA9003.*empty branch"
      severity: warning
